# Generated by cpp4r: do not edit by hand

#' @title OLS coefficients as a matrix
#' @param y response matrix (N*1)
#' @param x design matrix (N*P)
#' @return coefficient matrix (P*1)
#' @export
ols_mat <- function(y, x) {
	.Call(`_armadillo4rtest_ols_mat`, y, x)
}

#' @title OLS coefficients as a vector
#' @param y response matrix (N*1)
#' @param x design matrix (N*P)
#' @return coefficient vector (P)
#' @export
ols_dbl <- function(y, x) {
	.Call(`_armadillo4rtest_ols_dbl`, y, x)
}

#' @title Eigenvalues of a symmetric matrix as a matrix
#' @param x symmetric numeric matrix (N*N)
#' @return eigenvalue matrix (N*1)
#' @export
eigen_sym_mat <- function(x) {
	.Call(`_armadillo4rtest_eigen_sym_mat`, x)
}

#' @title Eigenvalues of a symmetric matrix as a vector
#' @param x symmetric numeric matrix (N*N)
#' @return eigenvalue vector (N)
#' @export
eigen_sym_dbl <- function(x) {
	.Call(`_armadillo4rtest_eigen_sym_dbl`, x)
}

#' @title Eigenvalues of a general matrix (real and imaginary parts)
#' @param x numeric matrix (N*N)
#' @return list with elements `real` and `imag` (each N*1 matrix)
#' @export
eigen_gen_mat <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_mat`, x)
}

#' @title Eigenvalues of a general matrix as a complex matrix
#' @param x numeric matrix (N*N)
#' @return complex eigenvalue matrix (N*1)
#' @export
eigen_gen_mat_complex_wrapper <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_mat_complex_wrapper`, x)
}

#' @title Eigenvalues of a general matrix as a complex vector
#' @param x numeric matrix (N*N)
#' @return complex eigenvalue vector (N)
#' @export
eigen_gen_dbl_complex_wrapper <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_dbl_complex_wrapper`, x)
}

#' @title Eigenvalues of a general matrix without wrapper helpers
#' @param x numeric matrix (N*N)
#' @return list with elements `real` and `imag` (each N*1 matrix)
#' @export
eigen_gen_no_wrapper <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_no_wrapper`, x)
}

#' @title Cholesky decomposition
#' @param x symmetric positive definite numeric matrix (N*N)
#' @param type decomposition type: `"upper"` for upper triangular or `"lower"`
#'   for lower triangular
#' @return triangular factor matrix (N*N)
#' @export
chol_mat <- function(x, type) {
	.Call(`_armadillo4rtest_chol_mat`, x, type)
}

#' @title OLS coefficients via QR decomposition as a matrix
#' @param y response matrix (N*1)
#' @param x design matrix (N*P)
#' @param econ logical scalar; if `TRUE` uses the economic QR decomposition
#' @return coefficient matrix (P*1)
#' @export
ols_qr_mat <- function(y, x, econ) {
	.Call(`_armadillo4rtest_ols_qr_mat`, y, x, econ)
}

#' @title OLS coefficients via QR decomposition as a vector
#' @param y response matrix (N*1)
#' @param x design matrix (N*P)
#' @param econ logical scalar; if `TRUE` uses the economic QR decomposition
#' @return coefficient vector (P)
#' @export
ols_qr_dbl <- function(y, x, econ) {
	.Call(`_armadillo4rtest_ols_qr_dbl`, y, x, econ)
}

#' @title CAPM model
#' @param r returns matrix (N*1)
#' @param m market returns matrix (N*1)
#' @param f risk-free rate (scalar)
#' @return expected returns matrix (N*1)
#' @export
capm <- function(r, m, f) {
	.Call(`_armadillo4rtest_capm`, r, m, f)
}

#' @title Round-trip conversion via Col<double>
#' @param x numeric vector
#' @return numeric vector identical to input
#' @export
typedef_Col_double <- function(x) {
	.Call(`_armadillo4rtest_typedef_Col_double`, x)
}

#' @title Round-trip conversion via Col<int>
#' @param x integer vector
#' @return integer vector identical to input
#' @export
typedef_Col_int <- function(x) {
	.Call(`_armadillo4rtest_typedef_Col_int`, x)
}

#' @title Round-trip conversion via uvec (unsigned integer column vector)
#' @param x integer vector
#' @return integer vector identical to input
#' @export
typedef_uvec <- function(x) {
	.Call(`_armadillo4rtest_typedef_uvec`, x)
}

#' @title Round-trip conversion via Mat<double>
#' @param x numeric matrix
#' @return numeric matrix identical to input
#' @export
typedef_Mat_double <- function(x) {
	.Call(`_armadillo4rtest_typedef_Mat_double`, x)
}

#' @title Round-trip conversion via Mat<int>
#' @param x integer matrix
#' @return integer matrix identical to input
#' @export
typedef_Mat_int <- function(x) {
	.Call(`_armadillo4rtest_typedef_Mat_int`, x)
}

#' @title Round-trip conversion via SpMat<double>
#' @param x numeric matrix
#' @return numeric matrix identical to input
#' @export
typedef_SpMat_double <- function(x) {
	.Call(`_armadillo4rtest_typedef_SpMat_double`, x)
}

#' @title Round-trip conversion via SpMat<int>
#' @param x integer matrix
#' @return integer matrix identical to input
#' @export
typedef_SpMat_int <- function(x) {
	.Call(`_armadillo4rtest_typedef_SpMat_int`, x)
}

#' @title Dense matrix typedef exchangeability
#' @param x numeric matrix
#' @return list of 8 numeric matrices, each produced via a different Mat alias
#' @export
typedef_dblmat_exchangeability <- function(x) {
	.Call(`_armadillo4rtest_typedef_dblmat_exchangeability`, x)
}

#' @title Sparse matrix typedef exchangeability (double)
#' @param x numeric matrix
#' @return list of 3 numeric matrices, each produced via a different SpMat alias
#' @export
typedef_spmat_exchangeability <- function(x) {
	.Call(`_armadillo4rtest_typedef_spmat_exchangeability`, x)
}

#' @title Sparse matrix typedef exchangeability (integer)
#' @param x integer matrix
#' @return list of 3 integer matrices, each produced via a different integer SpMat alias
#' @export
typedef_spmat_int_exchangeability <- function(x) {
	.Call(`_armadillo4rtest_typedef_spmat_int_exchangeability`, x)
}

#' @title Random integer matrix using R's RNG
#' @param n integer scalar; number of rows and columns
#' @return integer matrix (N*N) with values in the range 0 to 9
#' @export
random_matrix_nxn <- function(n) {
	.Call(`_armadillo4rtest_random_matrix_nxn`, n)
}

#' @title Matrix arithmetic demo
#' @param a numeric matrix
#' @return numeric matrix combining scalar addition, matrix addition and
#'   multiplication, and element-wise multiplication
#' @export
matrix1_ <- function(a) {
	.Call(`_armadillo4rtest_matrix1_`, a)
}

#' @title Complex matrix construction demo
#' @param a numeric matrix used as real part
#' @return complex matrix constructed from two real matrices
#' @export
matrix2_ <- function(a) {
	.Call(`_armadillo4rtest_matrix2_`, a)
}

#' @title Column vector extraction demo
#' @param x numeric vector (length 10)
#' @param y numeric vector (length 10)
#' @return numeric vector: column 6 of a random 10*10 matrix plus `y` plus `x`
#' @export
column1_ <- function(x, y) {
	.Call(`_armadillo4rtest_column1_`, x, y)
}

#' @title Row vector extraction demo
#' @param x numeric vector (length 10)
#' @param y numeric vector (length 10)
#' @return numeric vector: row 6 of a random 10*10 matrix plus `y` plus `x`
#' @export
row1_ <- function(x, y) {
	.Call(`_armadillo4rtest_row1_`, x, y)
}

#' @title Cube (3-D array) construction and slice arithmetic demo
#' @param a numeric matrix (first slice)
#' @param b numeric matrix (second slice)
#' @return numeric matrix: sum of first slice of 2*cube plus second slice of
#'   element-wise cube square
#' @export
cube1_ <- function(a, b) {
	.Call(`_armadillo4rtest_cube1_`, a, b)
}

#' @title Field-of-matrices construction and arithmetic demo
#' @param a numeric matrix (first field element)
#' @param b numeric matrix (second field element)
#' @return numeric matrix: sum of two input matrices plus transpose of their sum
#' @export
field1_ <- function(a, b) {
	.Call(`_armadillo4rtest_field1_`, a, b)
}

#' @title Matrix dimension attributes
#' @param a numeric matrix
#' @return named integer vector with elements `n_rows`, `n_cols`, and `n_elem`
#' @export
attr1_ <- function(a) {
	.Call(`_armadillo4rtest_attr1_`, a)
}

#' @title Element access and nested-loop mutation demo
#' @param a numeric matrix
#' @return numeric matrix with each element increased by element (1,1) of the
#'   original matrix plus element 2 of a random vector
#' @export
access1_ <- function(a) {
	.Call(`_armadillo4rtest_access1_`, a)
}

#' @title Brace-initializer construction demo
#' @param a numeric matrix
#' @return numeric matrix: `a` plus a 2*2 brace-initialized matrix with diagonal
#'   shifted by a brace-initialized vector
#' @export
initialization1_ <- function(a) {
	.Call(`_armadillo4rtest_initialization1_`, a)
}

#' @title Matrix zeros fill demo
#' @param a numeric matrix
#' @return numeric matrix: sum of three zero-filled matrices of the same size
#' @export
zeros1_ <- function(a) {
	.Call(`_armadillo4rtest_zeros1_`, a)
}

#' @title Matrix ones fill demo
#' @param a numeric matrix
#' @return numeric matrix: sum of three ones-filled matrices of the same size
#' @export
ones1_ <- function(a) {
	.Call(`_armadillo4rtest_ones1_`, a)
}

#' @title Identity matrix construction demo
#' @param a numeric matrix
#' @return numeric matrix: sum of three identity matrices of the same size
#' @export
eye1_ <- function(a) {
	.Call(`_armadillo4rtest_eye1_`, a)
}

#' @title Random uniform matrix fill demo
#' @param a numeric matrix
#' @return numeric matrix: `a` plus two random uniform matrices of the same size
#' @export
randu1_ <- function(a) {
	.Call(`_armadillo4rtest_randu1_`, a)
}

#' @title Random normal matrix fill demo
#' @param a numeric matrix
#' @return numeric matrix: `a` plus two random normal matrices of the same size
#' @export
randn1_ <- function(a) {
	.Call(`_armadillo4rtest_randn1_`, a)
}

#' @title Random uniform matrix using R's RNG
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with uniform random values
#' @export
randu2_ <- function(n) {
	.Call(`_armadillo4rtest_randu2_`, n)
}

#' @title Random normal matrix using R's RNG
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with standard normal random values
#' @export
randn2_ <- function(n) {
	.Call(`_armadillo4rtest_randn2_`, n)
}

#' @title fill::value fill demo
#' @param a numeric matrix used to determine size
#' @return numeric matrix: sum of matrices filled with 200, 100, zeros, and ones
#' @export
fill1_ <- function(a) {
	.Call(`_armadillo4rtest_fill1_`, a)
}

#' @title imbue fill via C++ RNG demo
#' @param a numeric matrix
#' @return numeric matrix: `a` plus a matrix filled via Mersenne-twister uniform
#'   distribution
#' @export
imbue1_ <- function(a) {
	.Call(`_armadillo4rtest_imbue1_`, a)
}

#' @title imbue fill via R's RNG demo
#' @param a numeric matrix
#' @return numeric matrix: `a` plus a matrix filled via `unif_rand()`
#' @export
imbue2_ <- function(a) {
	.Call(`_armadillo4rtest_imbue2_`, a)
}

#' @title clean() small-value zeroing demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with near-zero elements set to zero
#' @export
clean1_ <- function(n) {
	.Call(`_armadillo4rtest_clean1_`, n)
}

#' @title replace() NaN-with-zero demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with diagonal NaNs replaced by zero
#' @export
replace1_ <- function(n) {
	.Call(`_armadillo4rtest_replace1_`, n)
}

#' @title clamp() value-clamping demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with values clamped to the interval 0.2 to 0.8
#' @export
clamp1_ <- function(n) {
	.Call(`_armadillo4rtest_clamp1_`, n)
}

#' @title transform() element-wise function application demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with 122 added to every element
#' @export
transform1_ <- function(n) {
	.Call(`_armadillo4rtest_transform1_`, n)
}

#' @title for_each() iteration demo on dense, sparse, and field containers
#' @param n integer scalar; container dimension
#' @return numeric matrix (N*N): sum of modified dense matrix, sparse matrix,
#'   and two zero field matrices
#' @export
for_each1_ <- function(n) {
	.Call(`_armadillo4rtest_for_each1_`, n)
}

#' @title set_size() memory allocation demo
#' @param n integer scalar; container dimension
#' @return numeric vector: sum of first columns of two matrices plus a vector,
#'   all of size N
#' @export
set_size1_ <- function(n) {
	.Call(`_armadillo4rtest_set_size1_`, n)
}

#' @title reshape() dimension reordering demo
#' @param n integer scalar; base dimension
#' @return numeric matrix ((N-1)*(N+1)) reshaped from an (N+1)*(N-1) matrix
#' @export
reshape1_ <- function(n) {
	.Call(`_armadillo4rtest_reshape1_`, n)
}

#' @title resize() dimension change demo
#' @param n integer scalar; base dimension
#' @return numeric matrix ((N-1)*(N+1)) resized from an (N+1)*(N-1) matrix
#' @export
resize1_ <- function(n) {
	.Call(`_armadillo4rtest_resize1_`, n)
}

#' @title copy_size() demo
#' @param n integer scalar; matrix dimension
#' @return named integer vector with `n_rows` and `n_cols` of the copied matrix
#' @export
copy_size1_ <- function(n) {
	.Call(`_armadillo4rtest_copy_size1_`, n)
}

#' @title reset() matrix clearing demo
#' @param n integer scalar; initial matrix dimension
#' @return named integer vector with `n_rows` and `n_cols` after reset (both 0)
#' @export
reset1_ <- function(n) {
	.Call(`_armadillo4rtest_reset1_`, n)
}

#' @title Submatrix and conditional element access demo
#' @param n integer scalar; matrix dimension (>= 5)
#' @return numeric matrix (5*5) after subview assignments and element modifications
#' @export
subview1_ <- function(n) {
	.Call(`_armadillo4rtest_subview1_`, n)
}

#' @title Subcube and slice subview access demo
#' @param n integer scalar; cube row/column dimension
#' @return numeric matrix: slice 0 plus slice 1 of a cube after subview
#'   assignments and conditional modifications
#' @export
subview2_ <- function(n) {
	.Call(`_armadillo4rtest_subview2_`, n)
}

#' @title Diagonal extraction and manipulation demo
#' @param n integer scalar; matrix dimension
#' @return numeric vector: sum of modified sparse and dense diagonals
#' @export
diagonal1_ <- function(n) {
	.Call(`_armadillo4rtest_diagonal1_`, n)
}

#' @title each_col() broadcast demo
#' @param n integer scalar; number of rows
#' @return numeric matrix (N*(N+1)): result of column-wise broadcasts and
#'   lambda operations
#' @export
each_col1_ <- function(n) {
	.Call(`_armadillo4rtest_each_col1_`, n)
}

#' @title each_row() broadcast demo
#' @param n integer scalar; number of columns
#' @return numeric matrix ((N+1)*N): result of row-wise broadcasts and
#'   lambda operations
#' @export
each_row1_ <- function(n) {
	.Call(`_armadillo4rtest_each_row1_`, n)
}

#' @title each_slice() broadcast demo
#' @param n integer scalar; cube row dimension
#' @return numeric matrix (N*(N+1)): sum of all slices after slice-wise
#'   broadcasts and lambda operations
#' @export
each_slice1_ <- function(n) {
	.Call(`_armadillo4rtest_each_slice1_`, n)
}

#' @title set_real() real-part assignment demo
#' @param n integer scalar; base matrix dimension
#' @return complex matrix ((N+1)*(N-1)) with real part set from a random matrix
#' @export
set_real1_ <- function(n) {
	.Call(`_armadillo4rtest_set_real1_`, n)
}

#' @title cx_mat construction from two real matrices demo
#' @param n integer scalar; base matrix dimension
#' @return complex matrix ((N-1)*(N+1)) constructed from two random real matrices
#' @export
set_real2_ <- function(n) {
	.Call(`_armadillo4rtest_set_real2_`, n)
}

#' @title set_imag() imaginary-part assignment demo
#' @param n integer scalar; base matrix dimension
#' @return complex matrix ((N+1)*(N-1)) with imaginary part set from a random matrix
#' @export
set_imag1_ <- function(n) {
	.Call(`_armadillo4rtest_set_imag1_`, n)
}

#' @title insert_cols() column insertion demo
#' @param n integer scalar; base matrix dimension
#' @return numeric matrix (3N-1)*(3N-1) with columns inserted
#' @export
insert_columns1_ <- function(n) {
	.Call(`_armadillo4rtest_insert_columns1_`, n)
}

#' @title insert_rows() row insertion demo
#' @param n integer scalar; base matrix dimension
#' @return numeric matrix (3N-1)*(3N-1) with rows inserted
#' @export
insert_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_insert_rows1_`, n)
}

#' @title insert_slices() cube insertion demo
#' @param n integer scalar; cube dimension
#' @return numeric matrix (N*N): element-wise sum over all slices of two
#'   modified cubes
#' @export
insert_slices1_ <- function(n) {
	.Call(`_armadillo4rtest_insert_slices1_`, n)
}

#' @title shed_col() / shed_cols() column removal demo
#' @param n integer scalar; initial number of rows
#' @return numeric matrix after removing 4 columns from an N*(5N) matrix
#' @export
shed_columns1_ <- function(n) {
	.Call(`_armadillo4rtest_shed_columns1_`, n)
}

#' @title shed_row() / shed_rows() row removal demo
#' @param n integer scalar; initial number of columns
#' @return numeric matrix after removing 4 rows from a (5N)*N matrix
#' @export
shed_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_shed_rows1_`, n)
}

#' @title shed_slice() / shed_slices() cube slice removal demo
#' @param n integer scalar; cube dimension
#' @return numeric matrix (N*N): sum over remaining slices after removing 4
#' @export
shed_slices1_ <- function(n) {
	.Call(`_armadillo4rtest_shed_slices1_`, n)
}

#' @title swap_cols() column swapping demo
#' @param n integer scalar; number of rows
#' @return numeric matrix (N*(5N)) after two column swaps
#' @export
swap_columns1_ <- function(n) {
	.Call(`_armadillo4rtest_swap_columns1_`, n)
}

#' @title swap_rows() row swapping demo
#' @param n integer scalar; number of columns
#' @return numeric matrix ((5N)*N) after two row swaps
#' @export
swap_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_swap_rows1_`, n)
}

#' @title swap() matrix swap demo
#' @param n integer scalar; dimension
#' @return numeric matrix: result is the original `B` after swapping contents
#'   with `A`
#' @export
swap1_ <- function(n) {
	.Call(`_armadillo4rtest_swap1_`, n)
}

#' @title memptr() raw memory pointer access demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with each element increased by 123 plus the
#'   corresponding element of a second random matrix
#' @export
memptr1_ <- function(n) {
	.Call(`_armadillo4rtest_memptr1_`, n)
}

#' @title colptr() column memory pointer access demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with first column elements increased by 123
#' @export
colptr1_ <- function(n) {
	.Call(`_armadillo4rtest_colptr1_`, n)
}

#' @title Element and column iterator demo on a matrix
#' @param n integer scalar; matrix row dimension
#' @return numeric matrix (N*(N+1)) after iterating all elements and column 1-N
#' @export
iterators1_ <- function(n) {
	.Call(`_armadillo4rtest_iterators1_`, n)
}

#' @title Element and slice iterator demo on a cube
#' @param n integer scalar; cube dimension
#' @return numeric matrix (N*(N+1)): sum over all slices after iterating
#' @export
iterators2_ <- function(n) {
	.Call(`_armadillo4rtest_iterators2_`, n)
}

#' @title Sparse matrix element iterator demo
#' @param n integer scalar; matrix row dimension
#' @return numeric matrix (N*(2N)): sparse matrix after incrementing all
#'   non-zero elements by 123
#' @export
iterators3_ <- function(n) {
	.Call(`_armadillo4rtest_iterators3_`, n)
}

#' @title Range-based for loop over a subview demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N) with subview elements set to 123
#' @export
iterators4_ <- function(n) {
	.Call(`_armadillo4rtest_iterators4_`, n)
}

#' @title front() and back() compatibility demo
#' @param n integer scalar; vector length
#' @return named numeric vector with `front` and `back` elements
#' @export
compatibility1_ <- function(n) {
	.Call(`_armadillo4rtest_compatibility1_`, n)
}

#' @title clear() matrix clearing demo
#' @param n integer scalar; initial matrix dimension
#' @return named integer vector with row count `before` (N) and `after` (0)
#' @export
compatibility2_ <- function(n) {
	.Call(`_armadillo4rtest_compatibility2_`, n)
}

#' @title as_col() matrix-to-column-vector conversion demo
#' @param n integer scalar; matrix row dimension
#' @return numeric vector: all elements of an N*(N+1) matrix stacked
#'   column-major
#' @export
as_col1_ <- function(n) {
	.Call(`_armadillo4rtest_as_col1_`, n)
}

#' @title as_row() matrix-to-row-vector conversion demo
#' @param n integer scalar; matrix row dimension
#' @return numeric vector: all elements of an N*(N+1) matrix stacked row-major
#' @export
as_row1_ <- function(n) {
	.Call(`_armadillo4rtest_as_row1_`, n)
}

#' @title col_as_mat() cube column extraction demo
#' @param n integer scalar; cube row dimension
#' @return list with 4 slice matrices and the extracted `col_as_mat` matrix
#' @export
col_as_mat1_ <- function(n) {
	.Call(`_armadillo4rtest_col_as_mat1_`, n)
}

#' @title row_as_mat() cube row extraction demo
#' @param n integer scalar; cube row dimension
#' @return list with 4 slice matrices and the extracted `row_as_mat` matrix
#' @export
row_as_mat1_ <- function(n) {
	.Call(`_armadillo4rtest_row_as_mat1_`, n)
}

#' @title as_dense() sparse-to-dense conversion demo
#' @param n integer scalar; sparse matrix dimension
#' @return numeric vector: dense column plus dense row-sum of a random sparse
#'   matrix
#' @export
as_dense1_ <- function(n) {
	.Call(`_armadillo4rtest_as_dense1_`, n)
}

#' @title Matrix transpose demo
#' @param n integer scalar; matrix row dimension
#' @return numeric matrix ((N+1)*N): transpose of an N*(N+1) random matrix
#' @export
transpose1_ <- function(n) {
	.Call(`_armadillo4rtest_transpose1_`, n)
}

#' @title Sparse matrix transpose demo
#' @param n integer scalar; matrix row dimension
#' @return numeric matrix ((N+1)*N): transpose of a random sparse N*(N+1) matrix
#' @export
transpose2_ <- function(n) {
	.Call(`_armadillo4rtest_transpose2_`, n)
}

#' @title Matrix inverse and linear solve demo
#' @param a numeric square matrix (N*N)
#' @param b numeric vector (N)
#' @return numeric vector: `inv(a) %*% b`
#' @export
inverse1_ <- function(a, b) {
	.Call(`_armadillo4rtest_inverse1_`, a, b)
}

#' @title max() and min() of a matrix demo
#' @param n integer scalar; matrix dimension
#' @return named numeric vector with `max` and `min` of a random matrix
#' @export
maxmin1_ <- function(n) {
	.Call(`_armadillo4rtest_maxmin1_`, n)
}

#' @title index_max() and index_min() demo
#' @param n integer scalar; matrix dimension
#' @return named numeric vector: linear indices of max/min and four corner
#'   element values
#' @export
index_maxmin1_ <- function(n) {
	.Call(`_armadillo4rtest_index_maxmin1_`, n)
}

#' @title in_range() index validity check demo
#' @param n integer scalar; matrix row dimension
#' @return named logical vector indicating which row/column pairs are in range
#' @export
in_range1_ <- function(n) {
	.Call(`_armadillo4rtest_in_range1_`, n)
}

#' @title is_empty() emptiness check demo
#' @param n integer scalar; initial matrix dimension
#' @return named logical vector: emptiness before and after reset()
#' @export
is_empty1_ <- function(n) {
	.Call(`_armadillo4rtest_is_empty1_`, n)
}

#' @title is_vec() / is_colvec() / is_rowvec() predicate demo
#' @param n integer scalar; vector length
#' @return named logical vector of five vector-shape predicate results
#' @export
is_vec1_ <- function(n) {
	.Call(`_armadillo4rtest_is_vec1_`, n)
}

#' @title is_sorted() sortedness check demo
#' @param n integer scalar; vector length
#' @return named logical vector of four sortedness check results
#' @export
is_sorted1_ <- function(n) {
	.Call(`_armadillo4rtest_is_sorted1_`, n)
}

#' @title is_trimatu() / is_trimatl() triangularity check demo
#' @param n integer scalar; matrix dimension
#' @return named logical vector of three triangularity predicate results
#' @export
is_triangular1_ <- function(n) {
	.Call(`_armadillo4rtest_is_triangular1_`, n)
}

#' @title is_diagmat() diagonal matrix check demo
#' @param n integer scalar; matrix dimension
#' @return named logical vector of three diagonal-matrix predicate results
#' @export
is_diagonal1_ <- function(n) {
	.Call(`_armadillo4rtest_is_diagonal1_`, n)
}

#' @title is_square() square matrix check demo
#' @param n integer scalar; matrix dimension
#' @return named logical vector of three square-matrix predicate results
#' @export
is_square1_ <- function(n) {
	.Call(`_armadillo4rtest_is_square1_`, n)
}

#' @title is_symmetric() symmetry check demo
#' @param n integer scalar; matrix dimension
#' @return named logical vector of three symmetry predicate results
#' @export
is_symmetric1_ <- function(n) {
	.Call(`_armadillo4rtest_is_symmetric1_`, n)
}

#' @title is_hermitian() Hermitian check demo
#' @param n integer scalar; matrix dimension
#' @return named logical vector of three Hermitian predicate results
#' @export
is_hermitian1_ <- function(n) {
	.Call(`_armadillo4rtest_is_hermitian1_`, n)
}

#' @title is_sympd() symmetric positive definiteness check demo
#' @param n integer scalar; matrix dimension
#' @return named logical vector of three sym-pos-def predicate results
#' @export
is_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_is_sympd1_`, n)
}

#' @title is_zero() all-zero check demo (dense, cube, sparse)
#' @param n integer scalar; container dimension
#' @return named logical vector of three all-zero predicate results
#' @export
is_zero1_ <- function(n) {
	.Call(`_armadillo4rtest_is_zero1_`, n)
}

#' @title is_finite() finiteness check demo (dense, cube, sparse)
#' @param n integer scalar; container dimension
#' @return named logical vector of three finiteness predicate results
#' @export
is_finite1_ <- function(n) {
	.Call(`_armadillo4rtest_is_finite1_`, n)
}

#' @title has_inf() infinity check demo (dense, cube, sparse)
#' @param n integer scalar; container dimension
#' @return named logical vector of three has-infinity predicate results
#' @export
has_inf1_ <- function(n) {
	.Call(`_armadillo4rtest_has_inf1_`, n)
}

#' @title has_nan() NaN check demo (dense, cube, sparse)
#' @param n integer scalar; container dimension
#' @return named logical vector of three has-NaN predicate results
#' @export
has_nan1_ <- function(n) {
	.Call(`_armadillo4rtest_has_nan1_`, n)
}

#' @title linspace() linearly spaced vector demo
#' @param n integer scalar; number of points
#' @return numeric vector (N): sum of a column and a row linspace vector
#' @export
linspace1_ <- function(n) {
	.Call(`_armadillo4rtest_linspace1_`, n)
}

#' @title logspace() logarithmically spaced vector demo
#' @param n integer scalar; number of points
#' @return numeric vector (N): sum of a column and a row logspace vector
#' @export
logspace1_ <- function(n) {
	.Call(`_armadillo4rtest_logspace1_`, n)
}

#' @title regspace() regularly spaced vector demo
#' @param delta numeric scalar; spacing between elements
#' @return numeric vector: sum of a column and a row regspace vector
#' @export
regspace1_ <- function(delta) {
	.Call(`_armadillo4rtest_regspace1_`, delta)
}

#' @title randperm() random permutation demo
#' @param n integer scalar; permutation size
#' @param m integer scalar; number of elements to draw
#' @return integer vector: concatenation of a full and a partial permutation
#' @export
randperm1_ <- function(n, m) {
	.Call(`_armadillo4rtest_randperm1_`, n, m)
}

#' @title eye() identity matrix generation demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sum of three identity matrices of different types
#' @export
eye2_ <- function(n) {
	.Call(`_armadillo4rtest_eye2_`, n)
}

#' @title ones() ones-filled container generation demo
#' @param n integer scalar; container dimension
#' @return numeric matrix (N*N): sum of various ones-filled vectors, matrices,
#'   and a cube slice
#' @export
ones2_ <- function(n) {
	.Call(`_armadillo4rtest_ones2_`, n)
}

#' @title zeros() zeros-filled container generation demo
#' @param n integer scalar; container dimension
#' @return numeric matrix (N*N): sum of various zeros-filled vectors, matrices,
#'   and a cube slice
#' @export
zeros2_ <- function(n) {
	.Call(`_armadillo4rtest_zeros2_`, n)
}

#' @title randu() uniform random generation with optional distribution params demo
#' @param n integer scalar; container dimension
#' @return numeric matrix (N*N): sum of uniform random containers with and
#'   without distribution parameters
#' @export
randu3_ <- function(n) {
	.Call(`_armadillo4rtest_randu3_`, n)
}

#' @title randn() normal random generation with optional distribution params demo
#' @param n integer scalar; container dimension
#' @return numeric matrix (N*N): sum of normal random containers with and
#'   without distribution parameters
#' @export
randn3_ <- function(n) {
	.Call(`_armadillo4rtest_randn3_`, n)
}

#' @title randi() integer random generation with optional distribution params demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sum of integer random matrices with and
#'   without distribution parameters
#' @export
randg3_ <- function(n) {
	.Call(`_armadillo4rtest_randg3_`, n)
}

#' @title speye() sparse identity matrix generation demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): dense form of a sparse identity matrix
#' @export
speye1_ <- function(n) {
	.Call(`_armadillo4rtest_speye1_`, n)
}

#' @title spones() sparse nonzero-to-ones conversion demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): dense form of a sparse matrix with nonzeros
#'   replaced by ones
#' @export
spones1_ <- function(n) {
	.Call(`_armadillo4rtest_spones1_`, n)
}

#' @title sprandu() random sparse uniform matrix generation demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): dense form of a random sparse matrix
#' @export
sprandu1_ <- function(n) {
	.Call(`_armadillo4rtest_sprandu1_`, n)
}

#' @title sprandn() random sparse normal matrix generation demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): dense form of a random normal sparse matrix
#' @export
sprandn1_ <- function(n) {
	.Call(`_armadillo4rtest_sprandn1_`, n)
}

#' @title toeplitz() and circ_toeplitz() matrix generation demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sum of a Toeplitz and a circulant Toeplitz
#'   matrix
#' @export
toeplitz1_ <- function(n) {
	.Call(`_armadillo4rtest_toeplitz1_`, n)
}

#' @title abs() element-wise absolute value demo (real and complex)
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sum of abs(real matrix) and abs(complex matrix)
#' @export
abs1_ <- function(n) {
	.Call(`_armadillo4rtest_abs1_`, n)
}

#' @title accu() element accumulation and multiply-accumulate demo
#' @param n integer scalar; matrix dimension
#' @return numeric scalar: sum of all elements of A plus sum of A element-wise
#'   multiplied by B
#' @export
accu1_ <- function(n) {
	.Call(`_armadillo4rtest_accu1_`, n)
}

#' @title affmul() affine matrix-vector multiplication demo
#' @param n integer scalar; row dimension
#' @return numeric vector (N): result of `A[1:N, 1:N] %*% B + A[, N+1]`
#' @export
affmul1_ <- function(n) {
	.Call(`_armadillo4rtest_affmul1_`, n)
}

#' @title all() all-elements-nonzero check demo
#' @param n integer scalar; container dimension
#' @return logical vector of four all() check results
#' @export
all1_ <- function(n) {
	.Call(`_armadillo4rtest_all1_`, n)
}

#' @title any() any-element-nonzero check demo
#' @param n integer scalar; container dimension
#' @return logical vector of four any() check results
#' @export
any1_ <- function(n) {
	.Call(`_armadillo4rtest_any1_`, n)
}

#' @title approx_equal() approximate equality check demo
#' @param n integer scalar; matrix dimension
#' @return logical scalar: `TRUE` if all three approximate equality checks pass
#' @export
approx_equal1_ <- function(n) {
	.Call(`_armadillo4rtest_approx_equal1_`, n)
}

#' @title arg() complex argument (phase angle) demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): element-wise phase angles of a complex matrix
#' @export
arg1_ <- function(n) {
	.Call(`_armadillo4rtest_arg1_`, n)
}

#' @title as_scalar() expression-to-scalar conversion demo
#' @param n integer scalar; vector/matrix dimension
#' @return numeric scalar: sum of four scalar expressions involving
#'   dot/quadratic products
#' @export
as_scalar1_ <- function(n) {
	.Call(`_armadillo4rtest_as_scalar1_`, n)
}

#' @title clamp() functional form demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sum of three clamped versions of a random
#'   matrix
#' @export
clamp2_ <- function(n) {
	.Call(`_armadillo4rtest_clamp2_`, n)
}

#' @title cond() matrix condition number demo
#' @param n integer scalar; matrix dimension
#' @return numeric scalar: condition number of the N*N identity matrix (1)
#' @export
cond1_ <- function(n) {
	.Call(`_armadillo4rtest_cond1_`, n)
}

#' @title conj() complex conjugate demo
#' @param n integer scalar; matrix dimension
#' @return complex matrix (N*N): complex conjugate of a random complex matrix
#' @export
conj1_ <- function(n) {
	.Call(`_armadillo4rtest_conj1_`, n)
}

#' @title conv_to() type conversion demo (mat to fmat, vec to std::vector)
#' @param n integer scalar; matrix dimension
#' @return numeric vector: round-trip conversion through fmat and std::vector
#' @export
conv_to1_ <- function(n) {
	.Call(`_armadillo4rtest_conv_to1_`, n)
}

#' @title cross() cross product demo
#' @param n integer scalar; vector length (must be 3)
#' @return numeric vector (3): cross product of two random vectors
#' @export
cross1_ <- function(n) {
	.Call(`_armadillo4rtest_cross1_`, n)
}

#' @title cumsum() cumulative sum along different dimensions demo
#' @param n integer scalar; container dimension
#' @return numeric vector (3): accumulated sums of column-wise, row-wise, and
#'   vector cumulative sums
#' @export
cumsum1_ <- function(n) {
	.Call(`_armadillo4rtest_cumsum1_`, n)
}

#' @title cumprod() cumulative product along different dimensions demo
#' @param n integer scalar; container dimension
#' @return numeric vector (3): accumulated products of column-wise, row-wise,
#'   and vector cumulative products
#' @export
cumprod1_ <- function(n) {
	.Call(`_armadillo4rtest_cumprod1_`, n)
}

#' @title det() matrix determinant demo (two calling forms)
#' @param n integer scalar; matrix dimension
#' @return numeric vector (3): determinant of A, determinant of B, and success
#'   flag of the status-returning form
#' @export
det1_ <- function(n) {
	.Call(`_armadillo4rtest_det1_`, n)
}

#' @title diagmat() diagonal matrix construction demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sum of diagonal matrices built from a full
#'   matrix and a vector
#' @export
diagmat1_ <- function(n) {
	.Call(`_armadillo4rtest_diagmat1_`, n)
}

#' @title diagvec() diagonal extraction demo (super and sub-diagonal)
#' @param n integer scalar; matrix dimension
#' @return numeric vector (N-1): sum of first upper and lower diagonals
#' @export
diagvec1_ <- function(n) {
	.Call(`_armadillo4rtest_diagvec1_`, n)
}

#' @title diags() banded matrix construction demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): lower triangular banded matrix
#' @export
diags1_ <- function(n) {
	.Call(`_armadillo4rtest_diags1_`, n)
}

#' @title spdiags() sparse banded matrix construction demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): dense form of a lower triangular sparse banded
#'   matrix
#' @export
spdiags1_ <- function(n) {
	.Call(`_armadillo4rtest_spdiags1_`, n)
}

#' @title diff() first-order differences demo
#' @param n integer scalar; vector length
#' @return numeric matrix (N*2): original vector and its first differences
#' @export
diff1_ <- function(n) {
	.Call(`_armadillo4rtest_diff1_`, n)
}

#' @title dot(), cdot(), and norm_dot() inner product demo
#' @param n integer scalar; vector length
#' @return numeric vector (3): dot product, conjugate dot product, and
#'   normalized dot product
#' @export
dot1_ <- function(n) {
	.Call(`_armadillo4rtest_dot1_`, n)
}

#' @title eps() machine epsilon per element demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): element-wise machine epsilon of a random matrix
#' @export
eps1_ <- function(n) {
	.Call(`_armadillo4rtest_eps1_`, n)
}

#' @title expmat() matrix exponential demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): matrix exponential of a random matrix
#' @export
expmat1_ <- function(n) {
	.Call(`_armadillo4rtest_expmat1_`, n)
}

#' @title expmat_sym() symmetric matrix exponential demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): matrix exponential of a symmetrized random
#'   matrix
#' @export
expmat_sym1_ <- function(n) {
	.Call(`_armadillo4rtest_expmat_sym1_`, n)
}

#' @title find() conditional index search demo
#' @param n integer scalar; matrix dimension
#' @return list with three integer vectors of indices satisfying different
#'   conditions
#' @export
find1_ <- function(n) {
	.Call(`_armadillo4rtest_find1_`, n)
}

#' @title find_finite() finite element index search demo
#' @param n integer scalar; matrix dimension
#' @return integer vector: linear indices of finite elements
#' @export
find_finite1_ <- function(n) {
	.Call(`_armadillo4rtest_find_finite1_`, n)
}

#' @title find_nonfinite() non-finite element index search demo
#' @param n integer scalar; matrix dimension
#' @return integer vector: linear indices of non-finite (Inf/NaN) elements
#' @export
find_nonfinite1_ <- function(n) {
	.Call(`_armadillo4rtest_find_nonfinite1_`, n)
}

#' @title find_nan() NaN element index search demo
#' @param n integer scalar; matrix dimension
#' @return integer vector: linear indices of NaN elements
#' @export
find_nan1_ <- function(n) {
	.Call(`_armadillo4rtest_find_nan1_`, n)
}

#' @title find_unique() unique element index search demo
#' @param n integer scalar; matrix dimension
#' @return integer vector: linear indices of unique elements
#' @export
find_unique1_ <- function(n) {
	.Call(`_armadillo4rtest_find_unique1_`, n)
}

#' @title fliplr() / flipud() matrix flip demo
#' @param n integer scalar; matrix dimension
#' @return list with original matrix, left-right flip, and up-down flip
#' @export
flip1_ <- function(n) {
	.Call(`_armadillo4rtest_flip1_`, n)
}

#' @title imag() and real() complex part extraction demo
#' @param n integer scalar; matrix dimension
#' @return list with `imag` and `real` parts of a random complex matrix
#' @export
imag1_ <- function(n) {
	.Call(`_armadillo4rtest_imag1_`, n)
}

#' @title ind2sub() linear-index-to-subscript conversion demo
#' @param n integer scalar; matrix dimension
#' @return list with subscript vectors for a single index, a set of indices,
#'   and a cube index
#' @export
ind2sub1_ <- function(n) {
	.Call(`_armadillo4rtest_ind2sub1_`, n)
}

#' @title index_max() column/row-wise argmax demo
#' @param n integer scalar; matrix row dimension
#' @return numeric vector (2): max value in column 1 and max value in row N
#' @export
index_min1_ <- function(n) {
	.Call(`_armadillo4rtest_index_min1_`, n)
}

#' @title inplace_trans() in-place transpose demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): matrix after in-place transpose
#' @export
inplace_trans1_ <- function(n) {
	.Call(`_armadillo4rtest_inplace_trans1_`, n)
}

#' @title inplace_strans() in-place conjugate transpose demo
#' @param n integer scalar; matrix dimension
#' @return complex matrix (N*N): complex matrix after in-place conjugate
#'   transpose
#' @export
inplace_strans1_ <- function(n) {
	.Call(`_armadillo4rtest_inplace_strans1_`, n)
}

#' @title intersect() sorted-set intersection demo
#' @param n integer scalar; sequence length
#' @return integer vector: intersection of `n:1` and `2:(n+1)`
#' @export
intersect1_ <- function(n) {
	.Call(`_armadillo4rtest_intersect1_`, n)
}

#' @title join_rows() / join_cols() matrix concatenation demo
#' @param n integer scalar; matrix row dimension
#' @return list with three N*1 input matrices, their horizontal concatenation,
#'   and their vertical concatenation
#' @export
join_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_join_rows1_`, n)
}

#' @title join_slices() cube concatenation along slice dimension demo
#' @param n integer scalar; cube row/column dimension
#' @return list of 7 slice matrices from a cube formed by joining two cubes
#' @export
join_cubes1_ <- function(n) {
	.Call(`_armadillo4rtest_join_cubes1_`, n)
}

#' @title kron() Kronecker product demo
#' @param n integer scalar; base matrix dimension
#' @return numeric matrix (N*(N+1) * (N+1)*N): Kronecker product
#' @export
kron1_ <- function(n) {
	.Call(`_armadillo4rtest_kron1_`, n)
}

#' @title log_det() log-determinant demo (complex and real/sign forms)
#' @param n integer scalar; matrix dimension
#' @return list with complex form result (real/imag) and real form result
#'   (val/sign/ok)
#' @export
log_det1_ <- function(n) {
	.Call(`_armadillo4rtest_log_det1_`, n)
}

#' @title log_det_sympd() log-determinant of symmetric positive definite matrix
#'   demo
#' @param n integer scalar; matrix dimension
#' @return list with scalar log-det and a sub-list with scalar log-det plus
#'   success flag
#' @export
log_det_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_log_det_sympd1_`, n)
}

#' @title logmat() matrix logarithm demo
#' @param n integer scalar; matrix dimension
#' @return complex matrix (N*N): matrix logarithm of a random matrix
#' @export
logmat1_ <- function(n) {
	.Call(`_armadillo4rtest_logmat1_`, n)
}

#' @title logmat_sympd() logarithm of symmetric positive definite matrix demo
#' @param n integer scalar; matrix dimension
#' @return list with two elements: the result matrix and a sub-list with result
#'   matrix plus success flag
#' @export
logmat_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_logmat_sympd1_`, n)
}

#' @title max() column-wise, row-wise, and element-wise maximum demo
#' @param n integer scalar; matrix dimension
#' @return list with column max, row max, column max (dim=0), and element-wise
#'   max of two matrices
#' @export
max1_ <- function(n) {
	.Call(`_armadillo4rtest_max1_`, n)
}

#' @title nonzeros() non-zero element extraction demo
#' @param n integer scalar; matrix dimension
#' @return numeric vector: non-zero elements of a sparse-like matrix
#' @export
nonzeros1_ <- function(n) {
	.Call(`_armadillo4rtest_nonzeros1_`, n)
}

#' @title norm() vector norm demo (L1, L2, inf, Frobenius)
#' @param n integer scalar; vector length
#' @return named numeric vector (5): five norm values
#' @export
norm1_ <- function(n) {
	.Call(`_armadillo4rtest_norm1_`, n)
}

#' @title norm2est() 2-norm estimation demo
#' @param n integer scalar; matrix dimension
#' @return numeric scalar: estimated 2-norm of a random matrix
#' @export
norm2est1_ <- function(n) {
	.Call(`_armadillo4rtest_norm2est1_`, n)
}

#' @title normalise() column-wise and row-wise normalization demo
#' @param n integer scalar; matrix dimension
#' @return list with column-normalized and row-normalized matrices
#' @export
normalise1_ <- function(n) {
	.Call(`_armadillo4rtest_normalise1_`, n)
}

#' @title pow() element-wise power demo (scalar and matrix exponents)
#' @param n integer scalar; matrix dimension
#' @return list with squared matrix and element-wise powered matrix
#' @export
pow1_ <- function(n) {
	.Call(`_armadillo4rtest_pow1_`, n)
}

#' @title powmat() matrix power demo (two calling forms)
#' @param n integer scalar; matrix dimension
#' @return list with direct result and a sub-list with result plus success flag
#' @export
powmat1_ <- function(n) {
	.Call(`_armadillo4rtest_powmat1_`, n)
}

#' @title prod() column-wise and row-wise product demo
#' @param n integer scalar; matrix dimension
#' @return list with column products and row products
#' @export
prod1_ <- function(n) {
	.Call(`_armadillo4rtest_prod1_`, n)
}

#' @title rank() matrix rank demo (two calling forms)
#' @param n integer scalar; matrix dimension
#' @return list with scalar rank and a sub-list with scalar rank plus success
#'   flag
#' @export
rank1_ <- function(n) {
	.Call(`_armadillo4rtest_rank1_`, n)
}

#' @title rcond() reciprocal condition number demo
#' @param n integer scalar; matrix dimension
#' @return numeric scalar: reciprocal condition number of a random matrix
#' @export
rcond1_ <- function(n) {
	.Call(`_armadillo4rtest_rcond1_`, n)
}

#' @title repelem() element repetition demo
#' @param n integer scalar; matrix dimension
#' @return list with original and repeated (2x rows, 3x columns) matrix
#' @export
repelem1_ <- function(n) {
	.Call(`_armadillo4rtest_repelem1_`, n)
}

#' @title repmat() matrix tiling demo
#' @param n integer scalar; matrix dimension
#' @return list with original and tiled (2x rows, 3x columns) matrix
#' @export
repmat1_ <- function(n) {
	.Call(`_armadillo4rtest_repmat1_`, n)
}

#' @title reshape() functional form demo
#' @param n integer scalar; base matrix dimension
#' @return list with three matrices: original and two reshaped versions
#' @export
reshape2_ <- function(n) {
	.Call(`_armadillo4rtest_reshape2_`, n)
}

#' @title resize() functional form demo
#' @param n integer scalar; base matrix dimension
#' @return list with three matrices: original and two resized versions
#' @export
resize2_ <- function(n) {
	.Call(`_armadillo4rtest_resize2_`, n)
}

#' @title reverse() row-wise and column-wise reversal demo
#' @param n integer scalar; matrix dimension
#' @return list with original, row-reversed, and column-reversed matrix
#' @export
reverse1_ <- function(n) {
	.Call(`_armadillo4rtest_reverse1_`, n)
}

#' @title roots() polynomial root finding demo
#' @param n integer scalar; polynomial degree
#' @return complex vector (N-1): roots of a random degree-(N-1) polynomial
#' @export
roots1_ <- function(n) {
	.Call(`_armadillo4rtest_roots1_`, n)
}

#' @title shift() element shifting demo (negative and positive)
#' @param n integer scalar; matrix dimension
#' @return list with original, left-shifted, and right-shifted matrix
#' @export
shift1_ <- function(n) {
	.Call(`_armadillo4rtest_shift1_`, n)
}

#' @title shuffle() random row shuffling demo
#' @param n integer scalar; matrix dimension
#' @return list with original and shuffled matrix
#' @export
shuffle1_ <- function(n) {
	.Call(`_armadillo4rtest_shuffle1_`, n)
}

#' @title size() object size operations demo
#' @param n integer scalar; base matrix dimension
#' @return list of 7 matrices illustrating size() in construction, assignment,
#'   subview access, addition, and multiplication
#' @export
size1_ <- function(n) {
	.Call(`_armadillo4rtest_size1_`, n)
}

#' @title sort() ascending/descending column and row sort demo
#' @param n integer scalar; matrix dimension
#' @return list of 5 matrices: original, col-asc, col-desc, row-asc, row-desc
#' @export
sort1_ <- function(n) {
	.Call(`_armadillo4rtest_sort1_`, n)
}

#' @title sort_index() ascending and descending sort index demo
#' @param n integer scalar; matrix dimension
#' @return list with original matrix and two index vectors
#' @export
sort_index1_ <- function(n) {
	.Call(`_armadillo4rtest_sort_index1_`, n)
}

#' @title sqrtmat() matrix square root demo (two calling forms)
#' @param n integer scalar; matrix dimension
#' @return list with original matrix, two complex square roots, and success flag
#' @export
sqrtmat1_ <- function(n) {
	.Call(`_armadillo4rtest_sqrtmat1_`, n)
}

#' @title sqrtmat_sympd() symmetric positive definite matrix square root demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): real square root of a sym-pos-def matrix
#' @export
sqrtmat_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_sqrtmat_sympd1_`, n)
}

#' @title sum() column-wise and row-wise summation demo
#' @param n integer scalar; matrix dimension
#' @return list with row sums, column sums, and overall sum
#' @export
sum1_ <- function(n) {
	.Call(`_armadillo4rtest_sum1_`, n)
}

#' @title sum() column-wise and row-wise summation alternative form demo
#' @param n integer scalar; matrix dimension
#' @return list with row sums, column sums, and overall sum
#' @export
sum2_ <- function(n) {
	.Call(`_armadillo4rtest_sum2_`, n)
}

#' @title sub2ind() subscript-to-linear-index conversion demo
#' @param n integer scalar; matrix dimension
#' @return integer scalar: linear index of element (N-1, N-1)
#' @export
sub2ind1_ <- function(n) {
	.Call(`_armadillo4rtest_sub2ind1_`, n)
}

#' @title symmatu() upper-triangular symmetrization demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): symmetric matrix from upper triangle of input
#' @export
symmatu1_ <- function(n) {
	.Call(`_armadillo4rtest_symmatu1_`, n)
}

#' @title trace() matrix trace demo
#' @param n integer scalar; matrix dimension
#' @return numeric scalar: trace of a random N*N matrix
#' @export
trace1_ <- function(n) {
	.Call(`_armadillo4rtest_trace1_`, n)
}

#' @title trans() / .t() matrix transpose demo
#' @param n integer scalar; matrix dimension
#' @return list with original matrix and its transpose
#' @export
trans1_ <- function(n) {
	.Call(`_armadillo4rtest_trans1_`, n)
}

#' @title trapz() trapezoidal numerical integration demo
#' @param n integer scalar; number of integration points
#' @return numeric matrix (1*1): integral of sin(x) over 0 to pi
#' @export
trapz1_ <- function(n) {
	.Call(`_armadillo4rtest_trapz1_`, n)
}

#' @title trimatu() upper triangular extraction demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): upper triangular part of a random matrix
#' @export
trimatu1_ <- function(n) {
	.Call(`_armadillo4rtest_trimatu1_`, n)
}

#' @title trimatu_ind() upper triangular element indices demo
#' @param n integer scalar; matrix dimension
#' @return integer vector: linear indices of upper triangular elements
#' @export
trimatu_ind1_ <- function(n) {
	.Call(`_armadillo4rtest_trimatu_ind1_`, n)
}

#' @title unique() sorted unique element extraction demo
#' @param n integer scalar; matrix dimension
#' @return numeric vector: unique elements of a random matrix
#' @export
unique1_ <- function(n) {
	.Call(`_armadillo4rtest_unique1_`, n)
}

#' @title vecnorm() column-wise and row-wise vector norm demo
#' @param n integer scalar; matrix dimension
#' @return list with column L2 norms and row infinity norms
#' @export
vecnorm1_ <- function(n) {
	.Call(`_armadillo4rtest_vecnorm1_`, n)
}

#' @title vectorise() matrix-to-column-vector stacking demo
#' @param n integer scalar; matrix dimension
#' @return numeric vector (N^2): all elements of an N*N matrix in column-major
#'   order
#' @export
vectorise1_ <- function(n) {
	.Call(`_armadillo4rtest_vectorise1_`, n)
}

#' @title Miscellaneous element-wise math functions demo (exp, log, sqrt, round,
#'   sign)
#' @param n integer scalar; matrix dimension
#' @return list of 6 matrices: original plus exp, log, sqrt, round, and sign
#' @export
misc1_ <- function(n) {
	.Call(`_armadillo4rtest_misc1_`, n)
}

#' @title Trigonometric element-wise functions demo (cos, sin, tan, atan2, hypot)
#' @param n integer scalar; matrix dimension
#' @return list of 6 matrices: original plus cos, sin, tan, atan2, and hypot
#' @export
trig1_ <- function(n) {
	.Call(`_armadillo4rtest_trig1_`, n)
}

#' @title mean() column-wise, row-wise, and cube-wise mean demo
#' @param X numeric matrix (first input)
#' @param Y numeric matrix (second input used for cube)
#' @return list with three numeric vectors of mean values
#' @export
mean1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_mean1_`, X, Y)
}

#' @title median() column-wise and row-wise median demo
#' @param X numeric matrix (first input)
#' @param Y numeric matrix (second input)
#' @return list with three numeric vectors of median values
#' @export
median1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_median1_`, X, Y)
}

#' @title stddev() standard deviation demo (sample and population)
#' @param X numeric matrix (first input)
#' @param Y numeric matrix (second input)
#' @return list with three numeric vectors of standard deviation values
#' @export
stddev1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_stddev1_`, X, Y)
}

#' @title var() variance demo (sample and population)
#' @param X numeric matrix (first input)
#' @param Y numeric matrix (second input)
#' @return list with three numeric vectors of variance values
#' @export
var1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_var1_`, X, Y)
}

#' @title range() column-wise and row-wise value range demo
#' @param X numeric matrix (first input)
#' @param Y numeric matrix (second input)
#' @return list with two numeric vectors of range values
#' @export
range1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_range1_`, X, Y)
}

#' @title cov() covariance matrix demo (sample and population normalization)
#' @param X numeric matrix (first variable)
#' @param Y numeric matrix (second variable)
#' @return list with two covariance matrices
#' @export
cov1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_cov1_`, X, Y)
}

#' @title cor() correlation matrix demo (sample and population normalization)
#' @param X numeric matrix (first variable)
#' @param Y numeric matrix (second variable)
#' @return list with two correlation matrices
#' @export
cor1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_cor1_`, X, Y)
}

#' @title hist() histogram with fixed and custom bin edges demo
#' @param n integer scalar; number of random values
#' @return list with two integer count vectors
#' @export
hist1_ <- function(n) {
	.Call(`_armadillo4rtest_hist1_`, n)
}

#' @title histc() cumulative histogram demo
#' @param n integer scalar; number of random values
#' @return integer vector: bin counts using custom edges
#' @export
histc1_ <- function(n) {
	.Call(`_armadillo4rtest_histc1_`, n)
}

#' @title quantile() empirical quantile demo
#' @param n integer scalar; number of random values
#' @return numeric vector (5): 0th, 25th, 50th, 75th, 100th percentiles
#' @export
quantile1_ <- function(n) {
	.Call(`_armadillo4rtest_quantile1_`, n)
}

#' @title normpdf() normal probability density function demo (multiple forms)
#' @param n integer scalar; vector length
#' @return list with 5 density results using different parameter forms
#' @export
normpdf1_ <- function(n) {
	.Call(`_armadillo4rtest_normpdf1_`, n)
}

#' @title log_normpdf() log normal density function demo (multiple forms)
#' @param n integer scalar; vector length
#' @return list with 5 log-density results using different parameter forms
#' @export
lognormpdf1_ <- function(n) {
	.Call(`_armadillo4rtest_lognormpdf1_`, n)
}

#' @title normcdf() normal cumulative distribution function demo (multiple forms)
#' @param n integer scalar; vector length
#' @return list with 5 CDF results using different parameter forms
#' @export
normcdf1_ <- function(n) {
	.Call(`_armadillo4rtest_normcdf1_`, n)
}

#' @title mvnrnd() multivariate normal random sampling demo
#' @param n integer scalar; dimension of the distribution
#' @param m integer scalar; number of samples
#' @return numeric matrix (N*M): multivariate normal samples
#' @export
mvnrnd1_ <- function(n, m) {
	.Call(`_armadillo4rtest_mvnrnd1_`, n, m)
}

#' @title chi2rnd() chi-squared random sampling demo
#' @param n integer scalar; number of rows
#' @param m integer scalar; number of columns
#' @return list with two numeric matrices of chi-squared samples
#' @export
chi2rnd1_ <- function(n, m) {
	.Call(`_armadillo4rtest_chi2rnd1_`, n, m)
}

#' @title wishrnd() Wishart random matrix sampling demo
#' @param n integer scalar; matrix dimension
#' @return numeric matrix (N*N): sample from the Wishart distribution
#' @export
wishrnd1_ <- function(n) {
	.Call(`_armadillo4rtest_wishrnd1_`, n)
}

#' @title iwishrnd() inverse-Wishart random matrix sampling demo
#' @param n integer scalar; matrix dimension
#' @param d numeric scalar; degrees of freedom
#' @return numeric matrix (N*N): sample from the inverse-Wishart distribution
#' @export
iwishrnd1_ <- function(n, d) {
	.Call(`_armadillo4rtest_iwishrnd1_`, n, d)
}

#' @title kmeans() k-means clustering demo
#' @param n integer scalar; number of data points
#' @param d integer scalar; data dimensionality
#' @return list with success flag and cluster means matrix
#' @export
kmeans1_ <- function(n, d) {
	.Call(`_armadillo4rtest_kmeans1_`, n, d)
}

#' @title gmm_diag Gaussian mixture model fitting and inference demo
#' @param n integer scalar; number of data points
#' @param d integer scalar; data dimensionality
#' @return list with status, means, likelihoods, assignments, and histograms
#' @export
gmm1_ <- function(n, d) {
	.Call(`_armadillo4rtest_gmm1_`, n, d)
}

#' @title Matrix save and load demo (binary, text, CSV formats)
#' @param n integer scalar; matrix dimension
#' @return integer scalar: 0 on success
#' @export
saveload1_ <- function(n) {
	.Call(`_armadillo4rtest_saveload1_`, n)
}

#' @title Field-of-matrices save and load demo (binary and PPM formats)
#' @param n integer scalar; matrix dimension within the field
#' @param m integer scalar; number of matrices in the field
#' @return integer scalar: 0 on success
#' @export
saveload2_ <- function(n, m) {
	.Call(`_armadillo4rtest_saveload2_`, n, m)
}

#' @title conv() 1D convolution demo (full and same modes)
#' @param x numeric vector
#' @param y numeric vector
#' @return list with full-length and same-length convolution results
#' @export
conv1_ <- function(x, y) {
	.Call(`_armadillo4rtest_conv1_`, x, y)
}

#' @title conv2() 2D convolution demo (full and same modes)
#' @param x numeric matrix (kernel)
#' @param y numeric matrix (signal)
#' @return list with full-size and same-size 2D convolution results
#' @export
conv2_ <- function(x, y) {
	.Call(`_armadillo4rtest_conv2_`, x, y)
}

#' @title interp1() 1D interpolation demo (linear and nearest-neighbor)
#' @param n integer scalar; number of data points
#' @return numeric vector (2N): interpolated values at finer grid
#' @export
interp1_ <- function(n) {
	.Call(`_armadillo4rtest_interp1_`, n)
}

#' @title interp2() 2D interpolation demo
#' @param n integer scalar; grid dimension
#' @return numeric matrix: bilinearly interpolated surface on a finer grid
#' @export
interp2_ <- function(n) {
	.Call(`_armadillo4rtest_interp2_`, n)
}

#' @title fft() and ifft() 1D fast Fourier transform demo
#' @param x numeric vector
#' @return list with FFT result (real/imag) and inverse FFT result (real/imag)
#' @export
fft1_ <- function(x) {
	.Call(`_armadillo4rtest_fft1_`, x)
}

#' @title fft2() and ifft2() 2D fast Fourier transform demo
#' @param x numeric matrix
#' @return list with 2D FFT result (real/imag) and inverse 2D FFT result
#'   (real/imag)
#' @export
fft2_ <- function(x) {
	.Call(`_armadillo4rtest_fft2_`, x)
}

#' @title polyfit() polynomial curve fitting demo
#' @param n integer scalar; number of data points
#' @param m integer scalar; polynomial degree
#' @return numeric vector (M+1): fitted polynomial coefficients
#' @export
polyfit1_ <- function(n, m) {
	.Call(`_armadillo4rtest_polyfit1_`, n, m)
}

#' @title polyval() polynomial evaluation demo
#' @param n integer scalar; number of evaluation points
#' @param m integer scalar; polynomial degree
#' @return numeric vector (N): polynomial values evaluated at N points
#' @export
polyval1_ <- function(n, m) {
	.Call(`_armadillo4rtest_polyval1_`, n, m)
}

#' @title chol() Cholesky decomposition with pivoting demo
#' @param x numeric positive semi-definite matrix (N*N)
#' @param layout string scalar; `"upper"` or `"lower"`
#' @param output string scalar; `"matrix"` for pivot matrix, `"vector"` for
#'   pivot vector
#' @return list with success flag and triangular factor matrix
#' @export
chol1_ <- function(x, layout, output) {
	.Call(`_armadillo4rtest_chol1_`, x, layout, output)
}

#' @title eig_sym() symmetric eigendecomposition demo (two forms)
#' @param x symmetric numeric matrix (N*N)
#' @param method string scalar; `"dc"` (divide-and-conquer) or `"std"`
#' @return list with success flag, eigenvalue vector, and eigenvector matrix
#' @export
eig_sym1_ <- function(x, method) {
	.Call(`_armadillo4rtest_eig_sym1_`, x, method)
}

#' @title eig_gen() general eigendecomposition demo with optional balancing
#' @param x numeric matrix (N*N)
#' @param balance string scalar; `"balance"` or `"nobalance"`
#' @return list with success flag, complex eigenvalue vector, and complex
#'   eigenvector matrix
#' @export
eig_gen1_ <- function(x, balance) {
	.Call(`_armadillo4rtest_eig_gen1_`, x, balance)
}

#' @title eig_pair() generalized eigendecomposition (A*x = lambda*B*x) demo
#' @param a numeric matrix (N*N)
#' @param b numeric matrix (N*N)
#' @return list with success flag, complex eigenvalue vector, and complex
#'   eigenvector matrix
#' @export
eig_pair1_ <- function(a, b) {
	.Call(`_armadillo4rtest_eig_pair1_`, a, b)
}

#' @title hess() Hessenberg decomposition demo
#' @param x numeric matrix (N*N)
#' @return list with success flag and upper Hessenberg matrix
#' @export
hess1_ <- function(x) {
	.Call(`_armadillo4rtest_hess1_`, x)
}

#' @title inv() matrix inversion with approximate fallback demo
#' @param a numeric square matrix (N*N)
#' @return list with success flag and inverse matrix
#' @export
inv1_ <- function(a) {
	.Call(`_armadillo4rtest_inv1_`, a)
}

#' @title inv_sympd() symmetric positive definite matrix inversion demo
#' @param a numeric symmetric positive definite matrix (N*N)
#' @return list with success flag and inverse matrix
#' @export
inv_sympd1_ <- function(a) {
	.Call(`_armadillo4rtest_inv_sympd1_`, a)
}

#' @title lu() LU decomposition with pivoting demo
#' @param x numeric matrix (N*N)
#' @return list with success flag and L, U, P matrices
#' @export
lu1_ <- function(x) {
	.Call(`_armadillo4rtest_lu1_`, x)
}

#' @title null() null space computation demo
#' @param a numeric matrix (rows and first column zeroed)
#' @return list with success flag and null space matrix
#' @export
null1_ <- function(a) {
	.Call(`_armadillo4rtest_null1_`, a)
}

#' @title orth() orthonormal basis computation demo
#' @param a numeric matrix
#' @return list with success flag and orthonormal basis matrix
#' @export
orth1_ <- function(a) {
	.Call(`_armadillo4rtest_orth1_`, a)
}

#' @title pinv() Moore-Penrose pseudoinverse demo
#' @param a numeric matrix
#' @return list with pseudoinverse matrix
#' @export
pinv1_ <- function(a) {
	.Call(`_armadillo4rtest_pinv1_`, a)
}

#' @title qr() QR decomposition demo
#' @param x numeric matrix
#' @return list with success flag, Q matrix, and R matrix
#' @export
qr1_ <- function(x) {
	.Call(`_armadillo4rtest_qr1_`, x)
}

#' @title qr_econ() economic QR decomposition demo
#' @param x numeric matrix (N*P, N >= P)
#' @return list with success flag, thin Q matrix (N*P), and R matrix (P*P)
#' @export
qr_econ1_ <- function(x) {
	.Call(`_armadillo4rtest_qr_econ1_`, x)
}

#' @title qz() generalized Schur (QZ) decomposition demo
#' @param a numeric matrix (N*N)
#' @param b numeric matrix (N*N)
#' @param select string scalar; eigenvalue selection: `"lhp"`, `"rhp"`, `"iuc"`,
#'   `"ouc"`, or `"none"`
#' @return list with success flag and AA, BB, Q, Z matrices
#' @export
qz1_ <- function(a, b, select) {
	.Call(`_armadillo4rtest_qz1_`, a, b, select)
}

#' @title schur() Schur decomposition demo
#' @param x numeric matrix (N*N)
#' @return list with success flag, unitary matrix U, and quasi-upper-triangular
#'   matrix S
#' @export
schur1_ <- function(x) {
	.Call(`_armadillo4rtest_schur1_`, x)
}

#' @title solve() linear system solution demo
#' @param a numeric matrix (N*N)
#' @param b numeric matrix (N*M)
#' @return numeric matrix (N*M): solution X to A*X = B
#' @export
solve1_ <- function(a, b) {
	.Call(`_armadillo4rtest_solve1_`, a, b)
}

#' @title svd() singular value decomposition demo
#' @param x numeric matrix (M*N)
#' @return list with success flag, U matrix, singular value vector, and V matrix
#' @export
svd1_ <- function(x) {
	.Call(`_armadillo4rtest_svd1_`, x)
}

#' @title svd_econ() economic SVD demo
#' @param x numeric matrix (M*N)
#' @return list with thin U matrix, singular value vector, and thin V matrix
#' @export
svd_econ1_ <- function(x) {
	.Call(`_armadillo4rtest_svd_econ1_`, x)
}

#' @title sylvester() Sylvester equation solver (A*X + X*B = C) demo
#' @param a numeric matrix (N*N)
#' @param b numeric matrix (N*N)
#' @param c numeric matrix (N*N)
#' @return numeric matrix (N*N): solution X
#' @export
syl1_ <- function(a, b, c) {
	.Call(`_armadillo4rtest_syl1_`, a, b, c)
}

#' @title eigs_sym() sparse symmetric eigendecomposition demo
#' @param x numeric matrix (used to form a sparse sym-pos-def matrix)
#' @param method string scalar; `"lm"` (largest magnitude) or `"sm"`
#' @param k integer scalar; number of eigenvalues to compute
#' @return list with success flag, eigenvalue vector, and eigenvector matrix
#' @export
eig_sym2_ <- function(x, method, k) {
	.Call(`_armadillo4rtest_eig_sym2_`, x, method, k)
}

#' @title eigs_gen() sparse general eigendecomposition demo
#' @param x numeric matrix (used as a sparse matrix)
#' @param method string scalar; `"lm"` (largest magnitude) or `"sm"`
#' @param k integer scalar; number of eigenvalues to compute
#' @return list with success flag, complex eigenvalue vector, and complex
#'   eigenvector matrix
#' @export
eig_gen2_ <- function(x, method, k) {
	.Call(`_armadillo4rtest_eig_gen2_`, x, method, k)
}

#' @title svds() sparse singular value decomposition demo
#' @param x numeric matrix (used as a sparse matrix)
#' @param k integer scalar; number of singular values to compute
#' @return list with success flag, singular value vector, U matrix, and V matrix
#' @export
svds1_ <- function(x, k) {
	.Call(`_armadillo4rtest_svds1_`, x, k)
}

#' @title spsolve() sparse linear system solver demo
#' @param a numeric matrix (used as a sparse matrix N*N)
#' @param b numeric vector (N)
#' @param method string scalar; `"superlu"` or `"lapack"`
#' @return numeric vector (N): solution X to A*X = B
#' @export
spsolve1_ <- function(a, b, method) {
	.Call(`_armadillo4rtest_spsolve1_`, a, b, method)
}

#' @title OLS regression via QR decomposition
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric vector (P): OLS coefficient estimates
#' @export
ols_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_`, x, y)
}

#' @title Poisson regression via iteratively reweighted least squares
#' @param x design matrix (N*P)
#' @param y response vector (N) of non-negative counts
#' @return numeric vector (P): Poisson GLM coefficient estimates
#' @export
poisson_ <- function(x, y) {
	.Call(`_armadillo4rtest_poisson_`, x, y)
}

#' @title Convert a dgCMatrix to SpMat<double> and back
#' @param x sparse matrix in dgCMatrix format
#' @return dgCMatrix: round-trip result (values unchanged)
#' @export
test_dgCMatrix_to_SpMat <- function(x) {
	.Call(`_armadillo4rtest_test_dgCMatrix_to_SpMat`, x)
}

#' @title Convert any sparse Matrix to dgCMatrix via SpMat<double>
#' @param x sparse matrix (any CsparseMatrix, RsparseMatrix, or TsparseMatrix)
#' @return dgCMatrix: round-trip conversion result
#' @export
test_sparse_to_dgCMatrix <- function(x) {
	.Call(`_armadillo4rtest_test_sparse_to_dgCMatrix`, x)
}

#' @title Return dimensions of a sparse matrix
#' @param x sparse matrix (any format accepted by `as_SpMat()`)
#' @return integer vector (2): number of rows and columns
#' @export
test_sparse_dims <- function(x) {
	.Call(`_armadillo4rtest_test_sparse_dims`, x)
}

#' @title Round-trip R matrix via arma::mat (double precision)
#' @param x numeric matrix
#' @return numeric matrix identical to input
#' @export
implicit_conversion_double <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_double`, x)
}

#' @title Round-trip R matrix via arma::fmat (single precision)
#' @param x numeric matrix
#' @return numeric matrix (values may differ slightly due to float precision)
#' @export
implicit_conversion_float <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_float`, x)
}

#' @title Round-trip R matrix via arma::imat (signed integer)
#' @param x integer or numeric matrix
#' @return integer matrix
#' @export
implicit_conversion_int <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_int`, x)
}

#' @title Round-trip R matrix via arma::umat (unsigned integer)
#' @param x integer or numeric matrix
#' @return integer matrix (values truncated to unsigned range)
#' @export
implicit_conversion_uint <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_uint`, x)
}

#' @title OLS via QR using explicit as_doubles() conversion
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric vector (P): OLS coefficient estimates
#' @export
ols_traditional_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_traditional_`, x, y)
}

#' @title OLS via QR using cpp4r::as_sexp() for vec-to-doubles conversion
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric vector (P): OLS coefficient estimates
#' @export
ols_simplified_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified_`, x, y)
}

#' @title OLS via QR returning a matrix using cpp4r::as_sexp()
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric matrix (P*1): OLS coefficient estimates
#' @export
ols_simplified2_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified2_`, x, y)
}

#' @title OLS via QR using cpp4r::as_sexp() (form 3)
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric vector (P): OLS coefficient estimates
#' @export
ols_simplified3_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified3_`, x, y)
}

#' @title One-liner OLS using cpp4r::as_sexp() and as_col()
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric vector (P): OLS coefficient estimates
#' @export
ols_simplified4_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified4_`, x, y)
}

#' @title One-liner OLS returning a matrix using cpp4r::as_sexp() and as_col()
#' @param x design matrix (N*P)
#' @param y response vector (N)
#' @return numeric matrix (P*1): OLS coefficient estimates
#' @export
ols_simplified5_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified5_`, x, y)
}

#' @title Matrix addition using cpp4r::as_sexp()
#' @param a numeric matrix
#' @param b numeric matrix
#' @return numeric matrix: element-wise sum of `a` and `b`
#' @export
matrix_add_ <- function(a, b) {
	.Call(`_armadillo4rtest_matrix_add_`, a, b)
}

#' @title Integer matrix transpose using as_imat() and cpp4r::as_sexp()
#' @param x integer matrix
#' @return integer matrix: transpose of the input
#' @export
integer_transpose_ <- function(x) {
	.Call(`_armadillo4rtest_integer_transpose_`, x)
}

#' @title Unsigned integer matrix increment using as_umat() and cpp4r::as_sexp()
#' @param x integer matrix
#' @return integer matrix: input matrix with all elements incremented by 1
#' @export
uvec_example_ <- function(x) {
	.Call(`_armadillo4rtest_uvec_example_`, x)
}

#' @title Float matrix scaling using as_fmat() and cpp4r::as_sexp()
#' @param x numeric matrix
#' @return numeric matrix: input scaled by 2 (via single-precision arithmetic)
#' @export
fmat_example_ <- function(x) {
	.Call(`_armadillo4rtest_fmat_example_`, x)
}

#' @title R-to-Armadillo matrix conversion demo (double, int, float)
#' @param x numeric matrix
#' @param xi integer matrix
#' @return numeric matrix: A * t(A) where A is the double matrix
#' @export
mat_demo_ <- function(x, xi) {
	.Call(`_armadillo4rtest_mat_demo_`, x, xi)
}

#' @title R-to-Armadillo vector conversion demo (double and unsigned int)
#' @param y numeric vector
#' @param yi integer vector
#' @return numeric vector: element-wise square of the input
#' @export
vec_demo_ <- function(y, yi) {
	.Call(`_armadillo4rtest_vec_demo_`, y, yi)
}

#' @title Convert a list of matrices to a cube and compute column means per slice
#' @param slices list of numeric matrices (all same dimensions)
#' @return numeric matrix (N_slices * N_cols): column means for each slice
#' @export
cube_col_means_ <- function(slices) {
	.Call(`_armadillo4rtest_cube_col_means_`, slices)
}

#' @title Normalize each matrix in a list via field<mat>
#' @param mats list of numeric matrices
#' @return list of normalized numeric matrices
#' @export
field_mat_demo_ <- function(mats) {
	.Call(`_armadillo4rtest_field_mat_demo_`, mats)
}

#' @title Round-trip list of integer matrices via field<imat>
#' @param mats list of integer matrices
#' @return list of integer matrices identical to input
#' @export
field_imat_demo_ <- function(mats) {
	.Call(`_armadillo4rtest_field_imat_demo_`, mats)
}

#' @title Scale each vector in a list by 2 via field<vec>
#' @param vecs list of numeric vectors
#' @return list of numeric vectors, each scaled by 2
#' @export
field_vec_demo_ <- function(vecs) {
	.Call(`_armadillo4rtest_field_vec_demo_`, vecs)
}

#' @title Append "!" to each string
#' @param x character vector
#' @return character vector with "!" appended to every element
#' @export
field_str_demo_ <- function(x) {
	.Call(`_armadillo4rtest_field_str_demo_`, x)
}

#' @title Armadillo-to-R matrix conversion demo: t(A) * A
#' @param x numeric matrix
#' @return numeric matrix: crossproduct t(x) * x
#' @export
mat_out_demo_ <- function(x) {
	.Call(`_armadillo4rtest_mat_out_demo_`, x)
}

#' @title Armadillo-to-R vector conversion demo: normalise()
#' @param y numeric vector
#' @return numeric vector: L2-normalized input vector
#' @export
vec_out_demo_ <- function(y) {
	.Call(`_armadillo4rtest_vec_out_demo_`, y)
}

#' @title Create a random cube and return it as a list of matrices
#' @param n_rows integer scalar; number of rows per slice
#' @param n_cols integer scalar; number of columns per slice
#' @param n_slices integer scalar; number of slices
#' @return list of N_slices numeric matrices (each N_rows * N_cols)
#' @export
random_cube_ <- function(n_rows, n_cols, n_slices) {
	.Call(`_armadillo4rtest_random_cube_`, n_rows, n_cols, n_slices)
}

#' @title Round-trip list of matrices via Cube<int>
#' @param slices list of integer matrices
#' @return list of integer matrices identical to input
#' @export
integer_cube_roundtrip_ <- function(slices) {
	.Call(`_armadillo4rtest_integer_cube_roundtrip_`, slices)
}

#' @title Build a field of random vectors of specified sizes
#' @param sizes integer vector of vector lengths
#' @return list of numeric vectors, each filled with standard normal values
#' @export
build_field_ <- function(sizes) {
	.Call(`_armadillo4rtest_build_field_`, sizes)
}

#' @title Sort a vector using cpp4r::as_sexp() for the return value
#' @param y numeric vector
#' @return numeric vector: sorted in ascending order
#' @export
as_sexp_demo_ <- function(y) {
	.Call(`_armadillo4rtest_as_sexp_demo_`, y)
}
