# Generated by cpp4r: do not edit by hand

ols_mat <- function(y, x) {
	.Call(`_armadillo4rtest_ols_mat`, y, x)
}

ols_dbl <- function(y, x) {
	.Call(`_armadillo4rtest_ols_dbl`, y, x)
}

eigen_sym_mat <- function(x) {
	.Call(`_armadillo4rtest_eigen_sym_mat`, x)
}

eigen_sym_dbl <- function(x) {
	.Call(`_armadillo4rtest_eigen_sym_dbl`, x)
}

eigen_gen_mat <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_mat`, x)
}

eigen_gen_mat_complex_wrapper <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_mat_complex_wrapper`, x)
}

eigen_gen_dbl_complex_wrapper <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_dbl_complex_wrapper`, x)
}

eigen_gen_no_wrapper <- function(x) {
	.Call(`_armadillo4rtest_eigen_gen_no_wrapper`, x)
}

chol_mat <- function(x, type) {
	.Call(`_armadillo4rtest_chol_mat`, x, type)
}

ols_qr_mat <- function(y, x, econ) {
	.Call(`_armadillo4rtest_ols_qr_mat`, y, x, econ)
}

ols_qr_dbl <- function(y, x, econ) {
	.Call(`_armadillo4rtest_ols_qr_dbl`, y, x, econ)
}

capm <- function(r, m, f) {
	.Call(`_armadillo4rtest_capm`, r, m, f)
}

typedef_Col_double <- function(x) {
	.Call(`_armadillo4rtest_typedef_Col_double`, x)
}

typedef_Col_int <- function(x) {
	.Call(`_armadillo4rtest_typedef_Col_int`, x)
}

typedef_uvec <- function(x) {
	.Call(`_armadillo4rtest_typedef_uvec`, x)
}

typedef_Mat_double <- function(x) {
	.Call(`_armadillo4rtest_typedef_Mat_double`, x)
}

typedef_Mat_int <- function(x) {
	.Call(`_armadillo4rtest_typedef_Mat_int`, x)
}

typedef_SpMat_double <- function(x) {
	.Call(`_armadillo4rtest_typedef_SpMat_double`, x)
}

typedef_SpMat_int <- function(x) {
	.Call(`_armadillo4rtest_typedef_SpMat_int`, x)
}

typedef_dblmat_exchangeability <- function(x) {
	.Call(`_armadillo4rtest_typedef_dblmat_exchangeability`, x)
}

typedef_spmat_exchangeability <- function(x) {
	.Call(`_armadillo4rtest_typedef_spmat_exchangeability`, x)
}

typedef_spmat_int_exchangeability <- function(x) {
	.Call(`_armadillo4rtest_typedef_spmat_int_exchangeability`, x)
}

random_matrix_nxn <- function(n) {
	.Call(`_armadillo4rtest_random_matrix_nxn`, n)
}

matrix1_ <- function(a) {
	.Call(`_armadillo4rtest_matrix1_`, a)
}

matrix2_ <- function(a) {
	.Call(`_armadillo4rtest_matrix2_`, a)
}

column1_ <- function(x, y) {
	.Call(`_armadillo4rtest_column1_`, x, y)
}

row1_ <- function(x, y) {
	.Call(`_armadillo4rtest_row1_`, x, y)
}

cube1_ <- function(a, b) {
	.Call(`_armadillo4rtest_cube1_`, a, b)
}

field1_ <- function(a, b) {
	.Call(`_armadillo4rtest_field1_`, a, b)
}

attr1_ <- function(a) {
	.Call(`_armadillo4rtest_attr1_`, a)
}

access1_ <- function(a) {
	.Call(`_armadillo4rtest_access1_`, a)
}

initialization1_ <- function(a) {
	.Call(`_armadillo4rtest_initialization1_`, a)
}

zeros1_ <- function(a) {
	.Call(`_armadillo4rtest_zeros1_`, a)
}

ones1_ <- function(a) {
	.Call(`_armadillo4rtest_ones1_`, a)
}

eye1_ <- function(a) {
	.Call(`_armadillo4rtest_eye1_`, a)
}

randu1_ <- function(a) {
	.Call(`_armadillo4rtest_randu1_`, a)
}

randn1_ <- function(a) {
	.Call(`_armadillo4rtest_randn1_`, a)
}

randu2_ <- function(n) {
	.Call(`_armadillo4rtest_randu2_`, n)
}

randn2_ <- function(n) {
	.Call(`_armadillo4rtest_randn2_`, n)
}

fill1_ <- function(a) {
	.Call(`_armadillo4rtest_fill1_`, a)
}

imbue1_ <- function(a) {
	.Call(`_armadillo4rtest_imbue1_`, a)
}

imbue2_ <- function(a) {
	.Call(`_armadillo4rtest_imbue2_`, a)
}

clean1_ <- function(n) {
	.Call(`_armadillo4rtest_clean1_`, n)
}

replace1_ <- function(n) {
	.Call(`_armadillo4rtest_replace1_`, n)
}

clamp1_ <- function(n) {
	.Call(`_armadillo4rtest_clamp1_`, n)
}

transform1_ <- function(n) {
	.Call(`_armadillo4rtest_transform1_`, n)
}

for_each1_ <- function(n) {
	.Call(`_armadillo4rtest_for_each1_`, n)
}

set_size1_ <- function(n) {
	.Call(`_armadillo4rtest_set_size1_`, n)
}

reshape1_ <- function(n) {
	.Call(`_armadillo4rtest_reshape1_`, n)
}

resize1_ <- function(n) {
	.Call(`_armadillo4rtest_resize1_`, n)
}

copy_size1_ <- function(n) {
	.Call(`_armadillo4rtest_copy_size1_`, n)
}

reset1_ <- function(n) {
	.Call(`_armadillo4rtest_reset1_`, n)
}

subview1_ <- function(n) {
	.Call(`_armadillo4rtest_subview1_`, n)
}

subview2_ <- function(n) {
	.Call(`_armadillo4rtest_subview2_`, n)
}

diagonal1_ <- function(n) {
	.Call(`_armadillo4rtest_diagonal1_`, n)
}

each_col1_ <- function(n) {
	.Call(`_armadillo4rtest_each_col1_`, n)
}

each_row1_ <- function(n) {
	.Call(`_armadillo4rtest_each_row1_`, n)
}

each_slice1_ <- function(n) {
	.Call(`_armadillo4rtest_each_slice1_`, n)
}

set_real1_ <- function(n) {
	.Call(`_armadillo4rtest_set_real1_`, n)
}

set_real2_ <- function(n) {
	.Call(`_armadillo4rtest_set_real2_`, n)
}

set_imag1_ <- function(n) {
	.Call(`_armadillo4rtest_set_imag1_`, n)
}

insert_columns1_ <- function(n) {
	.Call(`_armadillo4rtest_insert_columns1_`, n)
}

insert_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_insert_rows1_`, n)
}

insert_slices1_ <- function(n) {
	.Call(`_armadillo4rtest_insert_slices1_`, n)
}

shed_columns1_ <- function(n) {
	.Call(`_armadillo4rtest_shed_columns1_`, n)
}

shed_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_shed_rows1_`, n)
}

shed_slices1_ <- function(n) {
	.Call(`_armadillo4rtest_shed_slices1_`, n)
}

swap_columns1_ <- function(n) {
	.Call(`_armadillo4rtest_swap_columns1_`, n)
}

swap_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_swap_rows1_`, n)
}

swap1_ <- function(n) {
	.Call(`_armadillo4rtest_swap1_`, n)
}

memptr1_ <- function(n) {
	.Call(`_armadillo4rtest_memptr1_`, n)
}

colptr1_ <- function(n) {
	.Call(`_armadillo4rtest_colptr1_`, n)
}

iterators1_ <- function(n) {
	.Call(`_armadillo4rtest_iterators1_`, n)
}

iterators2_ <- function(n) {
	.Call(`_armadillo4rtest_iterators2_`, n)
}

iterators3_ <- function(n) {
	.Call(`_armadillo4rtest_iterators3_`, n)
}

iterators4_ <- function(n) {
	.Call(`_armadillo4rtest_iterators4_`, n)
}

compatibility1_ <- function(n) {
	.Call(`_armadillo4rtest_compatibility1_`, n)
}

compatibility2_ <- function(n) {
	.Call(`_armadillo4rtest_compatibility2_`, n)
}

as_col1_ <- function(n) {
	.Call(`_armadillo4rtest_as_col1_`, n)
}

as_row1_ <- function(n) {
	.Call(`_armadillo4rtest_as_row1_`, n)
}

col_as_mat1_ <- function(n) {
	.Call(`_armadillo4rtest_col_as_mat1_`, n)
}

row_as_mat1_ <- function(n) {
	.Call(`_armadillo4rtest_row_as_mat1_`, n)
}

as_dense1_ <- function(n) {
	.Call(`_armadillo4rtest_as_dense1_`, n)
}

transpose1_ <- function(n) {
	.Call(`_armadillo4rtest_transpose1_`, n)
}

transpose2_ <- function(n) {
	.Call(`_armadillo4rtest_transpose2_`, n)
}

inverse1_ <- function(a, b) {
	.Call(`_armadillo4rtest_inverse1_`, a, b)
}

maxmin1_ <- function(n) {
	.Call(`_armadillo4rtest_maxmin1_`, n)
}

index_maxmin1_ <- function(n) {
	.Call(`_armadillo4rtest_index_maxmin1_`, n)
}

in_range1_ <- function(n) {
	.Call(`_armadillo4rtest_in_range1_`, n)
}

is_empty1_ <- function(n) {
	.Call(`_armadillo4rtest_is_empty1_`, n)
}

is_vec1_ <- function(n) {
	.Call(`_armadillo4rtest_is_vec1_`, n)
}

is_sorted1_ <- function(n) {
	.Call(`_armadillo4rtest_is_sorted1_`, n)
}

is_triangular1_ <- function(n) {
	.Call(`_armadillo4rtest_is_triangular1_`, n)
}

is_diagonal1_ <- function(n) {
	.Call(`_armadillo4rtest_is_diagonal1_`, n)
}

is_square1_ <- function(n) {
	.Call(`_armadillo4rtest_is_square1_`, n)
}

is_symmetric1_ <- function(n) {
	.Call(`_armadillo4rtest_is_symmetric1_`, n)
}

is_hermitian1_ <- function(n) {
	.Call(`_armadillo4rtest_is_hermitian1_`, n)
}

is_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_is_sympd1_`, n)
}

is_zero1_ <- function(n) {
	.Call(`_armadillo4rtest_is_zero1_`, n)
}

is_finite1_ <- function(n) {
	.Call(`_armadillo4rtest_is_finite1_`, n)
}

has_inf1_ <- function(n) {
	.Call(`_armadillo4rtest_has_inf1_`, n)
}

has_nan1_ <- function(n) {
	.Call(`_armadillo4rtest_has_nan1_`, n)
}

linspace1_ <- function(n) {
	.Call(`_armadillo4rtest_linspace1_`, n)
}

logspace1_ <- function(n) {
	.Call(`_armadillo4rtest_logspace1_`, n)
}

regspace1_ <- function(delta) {
	.Call(`_armadillo4rtest_regspace1_`, delta)
}

randperm1_ <- function(n, m) {
	.Call(`_armadillo4rtest_randperm1_`, n, m)
}

eye2_ <- function(n) {
	.Call(`_armadillo4rtest_eye2_`, n)
}

ones2_ <- function(n) {
	.Call(`_armadillo4rtest_ones2_`, n)
}

zeros2_ <- function(n) {
	.Call(`_armadillo4rtest_zeros2_`, n)
}

randu3_ <- function(n) {
	.Call(`_armadillo4rtest_randu3_`, n)
}

randn3_ <- function(n) {
	.Call(`_armadillo4rtest_randn3_`, n)
}

randg3_ <- function(n) {
	.Call(`_armadillo4rtest_randg3_`, n)
}

speye1_ <- function(n) {
	.Call(`_armadillo4rtest_speye1_`, n)
}

spones1_ <- function(n) {
	.Call(`_armadillo4rtest_spones1_`, n)
}

sprandu1_ <- function(n) {
	.Call(`_armadillo4rtest_sprandu1_`, n)
}

sprandn1_ <- function(n) {
	.Call(`_armadillo4rtest_sprandn1_`, n)
}

toeplitz1_ <- function(n) {
	.Call(`_armadillo4rtest_toeplitz1_`, n)
}

abs1_ <- function(n) {
	.Call(`_armadillo4rtest_abs1_`, n)
}

accu1_ <- function(n) {
	.Call(`_armadillo4rtest_accu1_`, n)
}

affmul1_ <- function(n) {
	.Call(`_armadillo4rtest_affmul1_`, n)
}

all1_ <- function(n) {
	.Call(`_armadillo4rtest_all1_`, n)
}

any1_ <- function(n) {
	.Call(`_armadillo4rtest_any1_`, n)
}

approx_equal1_ <- function(n) {
	.Call(`_armadillo4rtest_approx_equal1_`, n)
}

arg1_ <- function(n) {
	.Call(`_armadillo4rtest_arg1_`, n)
}

as_scalar1_ <- function(n) {
	.Call(`_armadillo4rtest_as_scalar1_`, n)
}

clamp2_ <- function(n) {
	.Call(`_armadillo4rtest_clamp2_`, n)
}

cond1_ <- function(n) {
	.Call(`_armadillo4rtest_cond1_`, n)
}

conj1_ <- function(n) {
	.Call(`_armadillo4rtest_conj1_`, n)
}

conv_to1_ <- function(n) {
	.Call(`_armadillo4rtest_conv_to1_`, n)
}

cross1_ <- function(n) {
	.Call(`_armadillo4rtest_cross1_`, n)
}

cumsum1_ <- function(n) {
	.Call(`_armadillo4rtest_cumsum1_`, n)
}

cumprod1_ <- function(n) {
	.Call(`_armadillo4rtest_cumprod1_`, n)
}

det1_ <- function(n) {
	.Call(`_armadillo4rtest_det1_`, n)
}

diagmat1_ <- function(n) {
	.Call(`_armadillo4rtest_diagmat1_`, n)
}

diagvec1_ <- function(n) {
	.Call(`_armadillo4rtest_diagvec1_`, n)
}

diags1_ <- function(n) {
	.Call(`_armadillo4rtest_diags1_`, n)
}

spdiags1_ <- function(n) {
	.Call(`_armadillo4rtest_spdiags1_`, n)
}

diff1_ <- function(n) {
	.Call(`_armadillo4rtest_diff1_`, n)
}

dot1_ <- function(n) {
	.Call(`_armadillo4rtest_dot1_`, n)
}

eps1_ <- function(n) {
	.Call(`_armadillo4rtest_eps1_`, n)
}

expmat1_ <- function(n) {
	.Call(`_armadillo4rtest_expmat1_`, n)
}

expmat_sym1_ <- function(n) {
	.Call(`_armadillo4rtest_expmat_sym1_`, n)
}

find1_ <- function(n) {
	.Call(`_armadillo4rtest_find1_`, n)
}

find_finite1_ <- function(n) {
	.Call(`_armadillo4rtest_find_finite1_`, n)
}

find_nonfinite1_ <- function(n) {
	.Call(`_armadillo4rtest_find_nonfinite1_`, n)
}

find_nan1_ <- function(n) {
	.Call(`_armadillo4rtest_find_nan1_`, n)
}

find_unique1_ <- function(n) {
	.Call(`_armadillo4rtest_find_unique1_`, n)
}

flip1_ <- function(n) {
	.Call(`_armadillo4rtest_flip1_`, n)
}

imag1_ <- function(n) {
	.Call(`_armadillo4rtest_imag1_`, n)
}

ind2sub1_ <- function(n) {
	.Call(`_armadillo4rtest_ind2sub1_`, n)
}

index_min1_ <- function(n) {
	.Call(`_armadillo4rtest_index_min1_`, n)
}

inplace_trans1_ <- function(n) {
	.Call(`_armadillo4rtest_inplace_trans1_`, n)
}

inplace_strans1_ <- function(n) {
	.Call(`_armadillo4rtest_inplace_strans1_`, n)
}

intersect1_ <- function(n) {
	.Call(`_armadillo4rtest_intersect1_`, n)
}

join_rows1_ <- function(n) {
	.Call(`_armadillo4rtest_join_rows1_`, n)
}

join_cubes1_ <- function(n) {
	.Call(`_armadillo4rtest_join_cubes1_`, n)
}

kron1_ <- function(n) {
	.Call(`_armadillo4rtest_kron1_`, n)
}

log_det1_ <- function(n) {
	.Call(`_armadillo4rtest_log_det1_`, n)
}

log_det_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_log_det_sympd1_`, n)
}

logmat1_ <- function(n) {
	.Call(`_armadillo4rtest_logmat1_`, n)
}

logmat_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_logmat_sympd1_`, n)
}

max1_ <- function(n) {
	.Call(`_armadillo4rtest_max1_`, n)
}

nonzeros1_ <- function(n) {
	.Call(`_armadillo4rtest_nonzeros1_`, n)
}

norm1_ <- function(n) {
	.Call(`_armadillo4rtest_norm1_`, n)
}

norm2est1_ <- function(n) {
	.Call(`_armadillo4rtest_norm2est1_`, n)
}

normalise1_ <- function(n) {
	.Call(`_armadillo4rtest_normalise1_`, n)
}

pow1_ <- function(n) {
	.Call(`_armadillo4rtest_pow1_`, n)
}

powmat1_ <- function(n) {
	.Call(`_armadillo4rtest_powmat1_`, n)
}

prod1_ <- function(n) {
	.Call(`_armadillo4rtest_prod1_`, n)
}

rank1_ <- function(n) {
	.Call(`_armadillo4rtest_rank1_`, n)
}

rcond1_ <- function(n) {
	.Call(`_armadillo4rtest_rcond1_`, n)
}

repelem1_ <- function(n) {
	.Call(`_armadillo4rtest_repelem1_`, n)
}

repmat1_ <- function(n) {
	.Call(`_armadillo4rtest_repmat1_`, n)
}

reshape2_ <- function(n) {
	.Call(`_armadillo4rtest_reshape2_`, n)
}

resize2_ <- function(n) {
	.Call(`_armadillo4rtest_resize2_`, n)
}

reverse1_ <- function(n) {
	.Call(`_armadillo4rtest_reverse1_`, n)
}

roots1_ <- function(n) {
	.Call(`_armadillo4rtest_roots1_`, n)
}

shift1_ <- function(n) {
	.Call(`_armadillo4rtest_shift1_`, n)
}

shuffle1_ <- function(n) {
	.Call(`_armadillo4rtest_shuffle1_`, n)
}

size1_ <- function(n) {
	.Call(`_armadillo4rtest_size1_`, n)
}

sort1_ <- function(n) {
	.Call(`_armadillo4rtest_sort1_`, n)
}

sort_index1_ <- function(n) {
	.Call(`_armadillo4rtest_sort_index1_`, n)
}

sqrtmat1_ <- function(n) {
	.Call(`_armadillo4rtest_sqrtmat1_`, n)
}

sqrtmat_sympd1_ <- function(n) {
	.Call(`_armadillo4rtest_sqrtmat_sympd1_`, n)
}

sum1_ <- function(n) {
	.Call(`_armadillo4rtest_sum1_`, n)
}

sum2_ <- function(n) {
	.Call(`_armadillo4rtest_sum2_`, n)
}

sub2ind1_ <- function(n) {
	.Call(`_armadillo4rtest_sub2ind1_`, n)
}

symmatu1_ <- function(n) {
	.Call(`_armadillo4rtest_symmatu1_`, n)
}

trace1_ <- function(n) {
	.Call(`_armadillo4rtest_trace1_`, n)
}

trans1_ <- function(n) {
	.Call(`_armadillo4rtest_trans1_`, n)
}

trapz1_ <- function(n) {
	.Call(`_armadillo4rtest_trapz1_`, n)
}

trimatu1_ <- function(n) {
	.Call(`_armadillo4rtest_trimatu1_`, n)
}

trimatu_ind1_ <- function(n) {
	.Call(`_armadillo4rtest_trimatu_ind1_`, n)
}

unique1_ <- function(n) {
	.Call(`_armadillo4rtest_unique1_`, n)
}

vecnorm1_ <- function(n) {
	.Call(`_armadillo4rtest_vecnorm1_`, n)
}

vectorise1_ <- function(n) {
	.Call(`_armadillo4rtest_vectorise1_`, n)
}

misc1_ <- function(n) {
	.Call(`_armadillo4rtest_misc1_`, n)
}

trig1_ <- function(n) {
	.Call(`_armadillo4rtest_trig1_`, n)
}

mean1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_mean1_`, X, Y)
}

median1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_median1_`, X, Y)
}

stddev1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_stddev1_`, X, Y)
}

var1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_var1_`, X, Y)
}

range1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_range1_`, X, Y)
}

cov1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_cov1_`, X, Y)
}

cor1_ <- function(X, Y) {
	.Call(`_armadillo4rtest_cor1_`, X, Y)
}

hist1_ <- function(n) {
	.Call(`_armadillo4rtest_hist1_`, n)
}

histc1_ <- function(n) {
	.Call(`_armadillo4rtest_histc1_`, n)
}

quantile1_ <- function(n) {
	.Call(`_armadillo4rtest_quantile1_`, n)
}

normpdf1_ <- function(n) {
	.Call(`_armadillo4rtest_normpdf1_`, n)
}

lognormpdf1_ <- function(n) {
	.Call(`_armadillo4rtest_lognormpdf1_`, n)
}

normcdf1_ <- function(n) {
	.Call(`_armadillo4rtest_normcdf1_`, n)
}

mvnrnd1_ <- function(n, m) {
	.Call(`_armadillo4rtest_mvnrnd1_`, n, m)
}

chi2rnd1_ <- function(n, m) {
	.Call(`_armadillo4rtest_chi2rnd1_`, n, m)
}

wishrnd1_ <- function(n) {
	.Call(`_armadillo4rtest_wishrnd1_`, n)
}

iwishrnd1_ <- function(n, d) {
	.Call(`_armadillo4rtest_iwishrnd1_`, n, d)
}

kmeans1_ <- function(n, d) {
	.Call(`_armadillo4rtest_kmeans1_`, n, d)
}

gmm1_ <- function(n, d) {
	.Call(`_armadillo4rtest_gmm1_`, n, d)
}

saveload1_ <- function(n) {
	.Call(`_armadillo4rtest_saveload1_`, n)
}

saveload2_ <- function(n, m) {
	.Call(`_armadillo4rtest_saveload2_`, n, m)
}

conv1_ <- function(x, y) {
	.Call(`_armadillo4rtest_conv1_`, x, y)
}

conv2_ <- function(x, y) {
	.Call(`_armadillo4rtest_conv2_`, x, y)
}

interp1_ <- function(n) {
	.Call(`_armadillo4rtest_interp1_`, n)
}

interp2_ <- function(n) {
	.Call(`_armadillo4rtest_interp2_`, n)
}

fft1_ <- function(x) {
	.Call(`_armadillo4rtest_fft1_`, x)
}

fft2_ <- function(x) {
	.Call(`_armadillo4rtest_fft2_`, x)
}

polyfit1_ <- function(n, m) {
	.Call(`_armadillo4rtest_polyfit1_`, n, m)
}

polyval1_ <- function(n, m) {
	.Call(`_armadillo4rtest_polyval1_`, n, m)
}

chol1_ <- function(x, layout, output) {
	.Call(`_armadillo4rtest_chol1_`, x, layout, output)
}

eig_sym1_ <- function(x, method) {
	.Call(`_armadillo4rtest_eig_sym1_`, x, method)
}

eig_gen1_ <- function(x, balance) {
	.Call(`_armadillo4rtest_eig_gen1_`, x, balance)
}

eig_pair1_ <- function(a, b) {
	.Call(`_armadillo4rtest_eig_pair1_`, a, b)
}

hess1_ <- function(x) {
	.Call(`_armadillo4rtest_hess1_`, x)
}

inv1_ <- function(a) {
	.Call(`_armadillo4rtest_inv1_`, a)
}

inv_sympd1_ <- function(a) {
	.Call(`_armadillo4rtest_inv_sympd1_`, a)
}

lu1_ <- function(x) {
	.Call(`_armadillo4rtest_lu1_`, x)
}

null1_ <- function(a) {
	.Call(`_armadillo4rtest_null1_`, a)
}

orth1_ <- function(a) {
	.Call(`_armadillo4rtest_orth1_`, a)
}

pinv1_ <- function(a) {
	.Call(`_armadillo4rtest_pinv1_`, a)
}

qr1_ <- function(x) {
	.Call(`_armadillo4rtest_qr1_`, x)
}

qr_econ1_ <- function(x) {
	.Call(`_armadillo4rtest_qr_econ1_`, x)
}

qz1_ <- function(a, b, select) {
	.Call(`_armadillo4rtest_qz1_`, a, b, select)
}

schur1_ <- function(x) {
	.Call(`_armadillo4rtest_schur1_`, x)
}

solve1_ <- function(a, b) {
	.Call(`_armadillo4rtest_solve1_`, a, b)
}

svd1_ <- function(x) {
	.Call(`_armadillo4rtest_svd1_`, x)
}

svd_econ1_ <- function(x) {
	.Call(`_armadillo4rtest_svd_econ1_`, x)
}

syl1_ <- function(a, b, c) {
	.Call(`_armadillo4rtest_syl1_`, a, b, c)
}

eig_sym2_ <- function(x, method, k) {
	.Call(`_armadillo4rtest_eig_sym2_`, x, method, k)
}

eig_gen2_ <- function(x, method, k) {
	.Call(`_armadillo4rtest_eig_gen2_`, x, method, k)
}

svds1_ <- function(x, k) {
	.Call(`_armadillo4rtest_svds1_`, x, k)
}

spsolve1_ <- function(a, b, method) {
	.Call(`_armadillo4rtest_spsolve1_`, a, b, method)
}

ols_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_`, x, y)
}

poisson_ <- function(x, y) {
	.Call(`_armadillo4rtest_poisson_`, x, y)
}

test_dgCMatrix_to_SpMat <- function(x) {
	.Call(`_armadillo4rtest_test_dgCMatrix_to_SpMat`, x)
}

implicit_conversion_double <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_double`, x)
}

implicit_conversion_float <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_float`, x)
}

implicit_conversion_int <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_int`, x)
}

implicit_conversion_uint <- function(x) {
	.Call(`_armadillo4rtest_implicit_conversion_uint`, x)
}

ols_traditional_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_traditional_`, x, y)
}

ols_simplified_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified_`, x, y)
}

ols_simplified2_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified2_`, x, y)
}

ols_simplified3_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified3_`, x, y)
}

ols_simplified4_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified4_`, x, y)
}

ols_simplified5_ <- function(x, y) {
	.Call(`_armadillo4rtest_ols_simplified5_`, x, y)
}

matrix_add_ <- function(a, b) {
	.Call(`_armadillo4rtest_matrix_add_`, a, b)
}

integer_transpose_ <- function(x) {
	.Call(`_armadillo4rtest_integer_transpose_`, x)
}

uvec_example_ <- function(x) {
	.Call(`_armadillo4rtest_uvec_example_`, x)
}

fmat_example_ <- function(x) {
	.Call(`_armadillo4rtest_fmat_example_`, x)
}
